"""Summarise E6 robustness runs for the AAMAS manuscript.

E6 repeats the two endpoint risk cells (p=.1 and p=.9) under two prompt
paraphrases and a temperature-zero decode.  The unit of analysis is a game;
``group_total / 6`` is the per-seat contribution.
"""

from __future__ import annotations

import pathlib
from typing import Dict

import pandas as pd


ROOT = pathlib.Path(__file__).resolve().parents[3]
RESULTS = ROOT / "results"
TABLES = ROOT / "paper" / "AAMAS" / "tables"

ARMS = {
    "temp0": RESULTS / "exp_baseline_temp0",
    "para1": RESULTS / "exp_para1",
    "para2": RESULTS / "exp_para2",
}
ORDER = [
    ("anthropic-claude-haiku-4-5-20251001", "Haiku"),
    ("google-gemini-3.5-flash-lite", "Flash-Lite"),
    ("openai-gpt-5.6-luna", "Luna"),
    ("qwen-qwen3-235b-a22b-instruct-2507", "Qwen"),
    ("xai-grok-4.20-0309-non-reasoning", "Grok"),
]


def load() -> pd.DataFrame:
    frames = []
    for arm, folder in ARMS.items():
        files = sorted(folder.glob("*/*/*.csv"))
        if not files:
            raise FileNotFoundError(f"No E6 CSV files found in {folder}")
        for path in files:
            frame = pd.read_csv(path)
            frame["arm"] = arm
            frame["model"] = frame["agent1_llm"]
            frame["own"] = frame["group_total"] / frame["n_players"]
            frames.append(frame)
    data = pd.concat(frames, ignore_index=True)
    expected = {0.1, 0.9}
    if set(data["risk_probability"].unique()) != expected:
        raise ValueError("E6 must contain exactly p=.1 and p=.9")
    return data


def fmt(value: float) -> str:
    return f"{value:.2f}"


def macros(data: pd.DataFrame) -> str:
    lines = [
        "% Generated by paper/AAMAS/analysis/e6_analysis.py -- DO NOT EDIT BY HAND.",
        f"\\newcommand{{\\EsixGames}}{{{len(data)}}}",
        f"\\newcommand{{\\EsixArms}}{{{data['arm'].nunique()}}}",
        f"\\newcommand{{\\EsixReps}}{{{int(data.groupby(['arm', 'model', 'risk_probability']).size().iloc[0])}}}",
        f"\\newcommand{{\\EsixLowRisk}}{{0.1}}",
        f"\\newcommand{{\\EsixHighRisk}}{{0.9}}",
    ]
    low = data[data.risk_probability == 0.1].own.mean()
    high = data[data.risk_probability == 0.9].own.mean()
    lines += [
        f"\\newcommand{{\\EsixLowOwn}}{{{fmt(low)}}}",
        f"\\newcommand{{\\EsixHighOwn}}{{{fmt(high)}}}",
        f"\\newcommand{{\\EsixPanelDelta}}{{{fmt(high - low)}}}",
    ]
    deltas: Dict[str, Dict[str, float]] = {}
    for model, short in ORDER:
        deltas[short] = {}
        for arm in ARMS:
            g = data[(data.model == model) & (data.arm == arm)]
            delta = g[g.risk_probability == 0.9].own.mean() - g[g.risk_probability == 0.1].own.mean()
            deltas[short][arm] = delta
    stable = [short for _, short in ORDER if short != "Grok"]
    stable_max = max(abs(v) for short in stable for v in deltas[short].values())
    grok = [deltas["Grok"][arm] for arm in ("temp0", "para1", "para2")]
    lines += [
        f"\\newcommand{{\\EsixStableModels}}{{{len(stable)}}}",
        f"\\newcommand{{\\EsixStableMaxDelta}}{{{fmt(stable_max)}}}",
        f"\\newcommand{{\\EsixGrokDeltaMin}}{{{fmt(min(grok))}}}",
        f"\\newcommand{{\\EsixGrokDeltaMax}}{{{fmt(max(grok))}}}",
    ]
    return "\n".join(lines) + "\n"


def table(data: pd.DataFrame) -> str:
    rows = [
        "% Generated by paper/AAMAS/analysis/e6_analysis.py -- DO NOT EDIT BY HAND.",
        "\\begin{table}[t]",
        "\\centering",
        "\\small",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        "Model & temp. 0 & paraphrase 1 & paraphrase 2 \\\\",
        "\\midrule",
    ]
    for model, short in ORDER:
        values = []
        for arm in ("temp0", "para1", "para2"):
            g = data[(data.model == model) & (data.arm == arm)]
            low = g[g.risk_probability == 0.1].own.mean()
            high = g[g.risk_probability == 0.9].own.mean()
            values.append(fmt(high - low))
        rows.append(f"{short} & " + " & ".join(values) + " \\\\")
    rows += [
        "\\bottomrule",
        "\\end{tabular}",
        "\\caption{E6 risk-sensitivity check. Entries are the change in per-seat contribution from $p=0.1$ to $p=0.9$; each cell averages ten games. The first column uses the baseline prompt at temperature zero.}",
        "\\label{tab:e6}",
        "\\end{table}",
    ]
    return "\n".join(rows) + "\n"


def main() -> None:
    data = load()
    TABLES.mkdir(parents=True, exist_ok=True)
    (TABLES / "e6_numbers.tex").write_text(macros(data), encoding="utf-8")
    (TABLES / "e6_table_robustness.tex").write_text(table(data), encoding="utf-8")
    print(f"E6: {len(data)} games; wrote e6_numbers.tex and e6_table_robustness.tex")


if __name__ == "__main__":
    main()
