"""Strategies behind the numbers: last round, simple rules, the Grok opening, equilibrium benchmark.

Run from the repository root:
    python paper/AAMAS/analysis/strategy.py

Reads results/ through crsd_data (read-only; never Legacy_Results/, never writes under results/).

Base-prompt corpus = exp_baseline, exp_evprobe, exp_mixed and the four scripted-partner
designs exp_bestresponse_{defect,coop,carry,cond}. One decision = one model seat in one round.

Writes ONLY
    paper/AAMAS/tables/num_strategy.tex
    paper/AAMAS/supplement/tables/s_strat_{endgame,rules,opening,equilibrium}.tex

STATISTICS. Unit of resampling = game. Every interval is a 95% percentile bootstrap with
2,000 resamples over games and a fixed seed (cd.SEED + a fixed offset per quantity). A share
of decisions is the pooled ratio (decisions in the state that satisfy the event over all
decisions in the state); its bootstrap resamples games and recomputes the pooled ratio.
The opening regression resamples games within design cells. Rounding is half-up.

A. LAST ROUND. need = 120 minus the pool at the start of round 10 (what the seats saw).
   Reached: need <= 0. Slack: 0 < need <= 10 (the other five paying 2 already reach 120).
   Pivotal: need == 12 (the seat's own 2 is needed). Late safe: rounds 7 to 9 whose starting
   pool is already >= 120. Luna self-play (exp_baseline + exp_evprobe): target rate of games
   whose pool after round 9 lies strictly between 108 and 120 (ahead of the fair pace)
   versus exactly 108 (on pace).
B. RULES. Exact-match accuracy of named rules; majority class; depth-5 decision tree
   (min 50 decisions per leaf) with game-grouped 5-fold CV, and the same tree without risk p.
C. GROK OPENING. exp_mixed games holding Grok and one other model. Grok's round-1 move is made
   before any history, and varies across repetitions of the same cell. Within cells
   (partner model x number of Grok seats x p), OLS of the partner's outcome on the mean
   Grok opening move, with cell fixed effects and the partner's own mean opening move as a
   control (dropped when it does not vary within cells). Outcomes: the partner's per-seat
   total over rounds 2 to 10; its mean payment per seat-round over rounds 2 to 10 whose
   starting pool is below 120 (before), and at or above 120 (after; games without such
   rounds drop out).
D. EQUILIBRIUM. Proposition 1 (p < 1): the Nash equilibria are x = 0, and X = T with
   x_i <= 40p. The first gives (1-p)40 per seat; the second exists only for p >= 0.5 and
   gives 20 per seat, which is >= (1-p)40 there. So the worst equilibrium welfare per seat
   is (1-p)40 at every p < 1. Share of exp_baseline self-play games whose expected welfare
   per seat is strictly below it, for 0.5 < p < 1 and for p < 0.5. p = 1 is excluded
   (welfare cannot fall below 0) and so is p = 0.5 (the two sets of equilibria tie).
"""
from __future__ import annotations

import re
import sys
import time
import warnings
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import GroupKFold
from sklearn.tree import DecisionTreeClassifier

sys.path.insert(0, str(Path(__file__).resolve().parent))
import crsd_data as cd      # noqa: E402

warnings.filterwarnings("ignore")

SOURCE = "paper/AAMAS/analysis/strategy.py"
HEADER = f"% Generated by {SOURCE}. Do not edit by hand."
OUT_T = cd.PAPER / "supplement" / "tables"
BASE = ("exp_baseline", "exp_evprobe", "exp_mixed", "exp_bestresponse_defect",
        "exp_bestresponse_coop", "exp_bestresponse_carry", "exp_bestresponse_cond")
SELF = ("exp_baseline", "exp_evprobe")
N_BOOT = 2000
TOL = 2.0          # percentage points a guarded value may drift from the text
OPTIONS = (0, 2, 4)
T = int(cd.TARGET)


# ------------------------------------------------------------------ formatting
def rnd(x: float, digits: int = 0) -> str:
    q = Decimal(1).scaleb(-digits)
    v = Decimal(repr(round(float(x), 9))).quantize(q, rounding=ROUND_HALF_UP)
    if v == 0:
        v = abs(v)
    s = f"{v:.{digits}f}"
    return "$-$" + s[1:] if s.startswith("-") else s


def pct(x: float) -> str:
    return rnd(100.0 * x, 0)


def pci(est, lo, hi) -> str:
    return f"{pct(est)} [{pct(lo)}, {pct(hi)}]"


def dci(est, lo, hi, digits=2) -> str:
    return f"{rnd(est, digits)} [{rnd(lo, digits)}, {rnd(hi, digits)}]"


FORBIDDEN = re.compile("|".join(["--", chr(0x2013), chr(0x2014), "exp_", "scripted:", "Legacy"]))


def write_tabular(name: str, lines) -> None:
    body = "\n".join(lines)
    bad = FORBIDDEN.search(body)
    if bad:
        raise RuntimeError(f"{name}: forbidden text {bad.group(0)!r}")
    if not (body.startswith(r"\begin{tabular}") and body.endswith(r"\end{tabular}")):
        raise RuntimeError(f"{name}: must contain exactly one tabular and nothing else")
    OUT_T.mkdir(parents=True, exist_ok=True)
    (OUT_T / name).write_text(HEADER + "\n" + body + "\n", encoding="utf-8")
    print(f"wrote {(OUT_T / name).relative_to(cd.REPO)}")


def note(text: str, ncols: int, width: float) -> str:
    """Note row set just below the table's natural width in the supplement's fonts, so it never stretches a column."""
    return rf"\multicolumn{{{ncols}}}{{@{{}}p{{{width}\linewidth}}@{{}}}}{{\footnotesize {text}}} \\"


def guard(label: str, value_pct: float, expected: float, tol: float = TOL) -> None:
    if abs(value_pct - expected) > tol:
        raise RuntimeError(f"{label}: {value_pct:.1f} drifted from {expected} by more than {tol} points; "
                           f"revisit the text")


# ------------------------------------------------------------------ bootstrap
def ratio_boot(event, gid, offset):
    """Pooled share of decisions with a game-level percentile bootstrap."""
    s = pd.DataFrame({"e": np.asarray(event, float), "g": np.asarray(gid)}).groupby("g").e.agg(["sum", "count"])
    num, den = s["sum"].to_numpy(float), s["count"].to_numpy(float)
    if len(num) == 0:
        raise ValueError("empty sample")
    idx = np.random.default_rng(cd.SEED + offset).integers(0, len(num), (N_BOOT, len(num)))
    draws = num[idx].sum(1) / den[idx].sum(1)
    return (num.sum() / den.sum(), float(np.percentile(draws, 2.5)), float(np.percentile(draws, 97.5)),
            len(num), int(den.sum()))


def mean_boot(values, offset):
    v = np.asarray(values, float)
    idx = np.random.default_rng(cd.SEED + offset).integers(0, len(v), (N_BOOT, len(v)))
    draws = v[idx].mean(1)
    return v.mean(), float(np.percentile(draws, 2.5)), float(np.percentile(draws, 97.5)), len(v)


# ------------------------------------------------------------------ decisions
def nearest(v: float) -> int:
    """Engine rule: nearest legal option, ties keep the lower one."""
    best, bd = OPTIONS[0], abs(v - OPTIONS[0])
    for o in OPTIONS[1:]:
        if abs(v - o) < bd:
            best, bd = o, abs(v - o)
    return best


def decisions(games: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for g in games.itertuples():
        S = g.strat.astype(int)
        names = [cd.SLUG.get(s) for s in g.llm]
        pot_start = np.r_[0.0, np.cumsum(S.sum(axis=0))[:-1]]
        for i, m in enumerate(names):
            if m is None:
                continue
            others = [j for j in range(cd.N_PLAYERS) if j != i]
            for t in range(cd.N_ROUNDS):
                need = cd.TARGET - pot_start[t]
                rl = cd.N_ROUNDS - t
                rows.append((g.gid, g.exp, round(g.p, 3), m, t + 1, int(S[i, t]),
                             int(S[i, t - 1]) if t else -1,
                             float(S[others, t - 1].mean()) if t else np.nan,
                             float(pot_start[t] - 12 * t), float(need), rl,
                             int(need <= 0), int(need > 24 * rl), float(need / (6 * rl)), int(g.reached)))
    return pd.DataFrame(rows, columns=["gid", "exp", "p", "model", "t", "a", "own_prev", "oth_prev", "pace",
                                       "need", "rl", "reached", "unreach", "req", "final_reached"])


# ============================================================================ A. last round
STATES = (("reached", "Target already reached"), ("slack", "Others' 2s suffice"),
          ("pivotal", "Own 2 is pivotal"), ("late", r"Rounds 7 to 9, reached"))


def endgame(D, games):
    last = D[D.t == 10]
    masks = {"reached": last.need <= 0, "slack": (last.need > 0) & (last.need <= 10), "pivotal": last.need == 12}
    res = {}
    for mi, m in enumerate(cd.MODELS):
        for si, (st, _) in enumerate(STATES):
            if st == "late":
                x = D[(D.model == m) & D.t.between(7, 9) & (D.reached == 1)]
            else:
                x = last[(last.model == m) & masks[st]]
            res[(m, st)] = ratio_boot((x.a == 0).to_numpy(), x.gid.to_numpy(), 100 + 10 * mi + si) if len(x) else None
    print("\n[A] P(pay 0): round 10 by state, and rounds 7-9 once reached (pooled decisions, game bootstrap)")
    for m in cd.MODELS:
        print(f"  {m:10} " + " | ".join(
            f"{st} {100 * r[0]:5.1f} [{100 * r[1]:.0f},{100 * r[2]:.0f}] g={r[3]} d={r[4]}" if r else f"{st} n/a"
            for st, r in ((s, res[(m, s)]) for s, _ in STATES)))

    sp = games[games.exp.isin(SELF)]
    tag = next(k for k, v in cd.SLUG.items() if v == "Luna")
    luna = sp[sp.llm.map(lambda l: all(s == tag for s in l))]
    pot9 = luna.pot.map(lambda x: float(x[8]))
    if (pot9 >= cd.TARGET).any():
        raise RuntimeError("a Luna self-play game already reached 120 before round 10; redefine 'ahead'")
    ahead = mean_boot(luna[(pot9 > 108) & (pot9 < cd.TARGET)].reached, 150)
    onpace = mean_boot(luna[pot9 == 108].reached, 151)
    print(f"  Luna self-play target rate: ahead {100 * ahead[0]:.1f}% [{100 * ahead[1]:.0f},{100 * ahead[2]:.0f}]"
          f" n={ahead[3]} | on pace {100 * onpace[0]:.1f}% [{100 * onpace[1]:.0f},{100 * onpace[2]:.0f}] n={onpace[3]}")

    for (m, st), want in {("Luna", "pivotal"): 1.6, ("Luna", "slack"): 53, ("Qwen", "pivotal"): 93,
                          ("Qwen", "slack"): 93, ("Qwen", "reached"): 80, ("Qwen", "late"): 1,
                          ("Haiku", "late"): 90, ("Flash-Lite", "late"): 96, ("Luna", "late"): 100}.items():
        guard(f"P(0) {m} {st}", 100 * res[(m, st)][0], want)
    guard("Luna ahead target rate", 100 * ahead[0], 27)
    guard("Luna on-pace target rate", 100 * onpace[0], 92)

    ncols = 1 + 2 * len(STATES)
    lines = [r"\begin{tabular}{@{}l" + "rr" * len(STATES) + "@{}}", r"\toprule",
             " & " + " & ".join(rf"\multicolumn{{2}}{{c}}{{{lab}}}" for _, lab in STATES) + r" \\",
             "".join(rf"\cmidrule(l){{{2 + 2 * k}-{3 + 2 * k}}}" for k in range(len(STATES))),
             "Model & " + " & ".join([r"Paid 0 (\%) & Games"] * len(STATES)) + r" \\", r"\midrule"]
    for m in cd.MODELS:
        cells = []
        for st, _ in STATES:
            r = res[(m, st)]
            cells += [pci(*r[:3]), str(r[3])] if r else ["n/a", "0"]
        lines.append(f"{cd.show(m)} & " + " & ".join(cells) + r" \\")
    lines += [r"\midrule",
              rf"\multicolumn{{{ncols}}}{{@{{}}l}}{{\textit{{{cd.show('Luna')} self-play: target reached (\%) by the pool after round 9}}}} \\",
              rf"Ahead of pace (110 to 118) & {pci(*ahead[:3])} & {ahead[3]} & \multicolumn{{{ncols - 3}}}{{l}}{{}} \\",
              rf"On pace (exactly 108) & {pci(*onpace[:3])} & {onpace[3]} & \multicolumn{{{ncols - 3}}}{{l}}{{}} \\",
              r"\midrule",
              note("Top: share of decisions paying 0 with a 95\\% bootstrap interval over games, and the number of games. "
                   "Round 10 is split by the pool the seats saw before deciding: at least 120 (reached); 110 to 118, "
                   "so the other five paying 2 already reach 120 (others' 2s suffice); exactly 108 (own 2 is pivotal). "
                   "The last pair of columns pools rounds 7 to 9 that start with the pool already at 120 or more. "
                   "Base-prompt games: self-play, mixed tables and scripted partners.", ncols, 0.9),
              r"\bottomrule", r"\end{tabular}"]
    write_tabular("s_strat_endgame.tex", lines)
    return res, ahead, onpace


# ============================================================================ B. rules
RULES = (("always2", "Always 2"), ("repeat", "Repeat own move"), ("copy", "Copy the group"),
         ("skipper", "Last-round skipper"), ("settled", "Stop when settled"), ("tracker", "Pool tracker"),
         ("riskneutral", "Risk-neutral step"))
RULE_TEXT = {"always2": "always 2", "repeat": "repeat own move", "copy": "copy the group",
             "skipper": "last-round skipper", "settled": "stop when settled", "tracker": "pool tracker",
             "riskneutral": "risk-neutral step"}
FEATS = ["own0", "own2", "own4", "first", "oth_prev", "pace12", "rl", "last", "reached", "unreach", "p", "req"]


def rule_predictions(d):
    t1 = (d.t == 1).to_numpy()
    settled = ((d.reached == 1) | (d.unreach == 1)).to_numpy()
    tracker = np.clip(np.ceil(d.req.to_numpy() / 2) * 2, 0, 4)
    return {
        "always2": np.full(len(d), 2),
        "repeat": np.where(t1, 2, d.own_prev.to_numpy()),
        "copy": np.where(t1, 2, d.oth_prev.fillna(2.0).map(nearest).to_numpy()),
        "skipper": np.where(d.t.to_numpy() == 10, 0, 2),
        "settled": np.where(settled, 0, 2),
        "tracker": np.where(settled, 0, tracker).astype(int),
        "riskneutral": np.where(d.p.to_numpy() >= 0.5, np.where(d.reached.to_numpy() == 1, 0, 2), 0),
    }


def featurize(d):
    X = pd.DataFrame({
        "own0": (d.own_prev == 0).astype(int), "own2": (d.own_prev == 2).astype(int),
        "own4": (d.own_prev == 4).astype(int), "first": (d.t == 1).astype(int),
        "oth_prev": d.oth_prev.fillna(2.0), "pace12": d.pace / 12.0, "rl": d.rl,
        "last": (d.t == 10).astype(int), "reached": d.reached, "unreach": d.unreach, "p": d.p,
        "req": d.req.clip(-2, 6)})
    return X[FEATS].to_numpy(float)


def cv_correct(X, y, groups):
    pred = np.zeros(len(y), int)
    for tr, te in GroupKFold(n_splits=5).split(X, y, groups):
        clf = DecisionTreeClassifier(max_depth=5, min_samples_leaf=50, random_state=0)
        pred[te] = clf.fit(X[tr], y[tr]).predict(X[te])
    return pred == y


def rules(D):
    d0 = D[D.exp.isin(BASE)]
    res = {}
    print("\n[B] exact-match accuracy over the base-prompt corpus (pooled decisions, game bootstrap)")
    for mi, m in enumerate(cd.MODELS):
        d = d0[d0.model == m].reset_index(drop=True)
        y, gid = d.a.to_numpy(), d.gid.to_numpy()
        r = {}
        for ri, (k, pr) in enumerate(rule_predictions(d).items()):
            r[k] = ratio_boot(pr == y, gid, 1000 + 100 * mi + ri)
        maj = int(pd.Series(y).mode()[0])
        r["majority"] = ratio_boot(y == maj, gid, 1000 + 100 * mi + 20)
        X = featurize(d)
        full = cv_correct(X, y, gid)
        nop = cv_correct(np.delete(X, FEATS.index("p"), axis=1), y, gid)
        r["tree"] = ratio_boot(full, gid, 1000 + 100 * mi + 21)
        r["treenop"] = ratio_boot(nop, gid, 1000 + 100 * mi + 22)
        best = max((k for k, _ in RULES), key=lambda k: r[k][0])
        r["dp"] = ratio_boot(nop.astype(float) - full.astype(float), gid, 1000 + 100 * mi + 23)
        best_correct = rule_predictions(d)[best] == y
        r["gain"] = ratio_boot(full.astype(float) - best_correct.astype(float), gid, 1000 + 100 * mi + 24)
        r["best"], r["maj_class"], r["n_games"], r["n_dec"] = best, maj, r["tree"][3], len(y)
        res[m] = r
        print(f"  {m:10} games={r['n_games']} decisions={len(y)} majority class={maj} best rule={best}")
        print("     " + "  ".join(f"{k}={100 * r[k][0]:.1f}[{100 * r[k][1]:.1f},{100 * r[k][2]:.1f}]"
                                  for k in [k for k, _ in RULES] + ["majority", "tree", "treenop"]))
        print(f"     without p minus with p = {100 * r['dp'][0]:+.2f} pp [{100 * r['dp'][1]:+.2f},{100 * r['dp'][2]:+.2f}]"
              f" | tree minus best rule = {100 * r['gain'][0]:+.2f} pp")

    want_best = {"Haiku": "settled", "Flash-Lite": "tracker", "Luna": "repeat", "Qwen": "skipper", "Grok": "repeat"}
    for m, k in want_best.items():
        if res[m]["best"] != k:
            raise RuntimeError(f"best named rule for {m} is now {res[m]['best']}, text says {k}")
    for m, want in {"Haiku": 86.5, "Flash-Lite": 98.9, "Luna": 95.4, "Qwen": 96.5, "Grok": 90.9}.items():
        guard(f"tree CV accuracy {m}", 100 * res[m]["tree"][0], want)
    drop_max = max(-res[m]["dp"][0] for m in cd.MODELS)
    if 100 * drop_max > 0.5:
        raise RuntimeError(f"removing risk p now costs {100 * drop_max:.2f} pp; the text says it costs nothing")

    ncols = 1 + len(cd.MODELS)
    head1 = " & ".join(rf"\multicolumn{{1}}{{c}}{{{cd.LINES[m][0]}}}" for m in cd.MODELS)
    head2 = " & ".join(rf"\multicolumn{{1}}{{c}}{{{cd.LINES[m][1]}}}" for m in cd.MODELS)
    lines = [r"\begin{tabular}{@{}l" + "c" * len(cd.MODELS) + "@{}}", r"\toprule",
             " & " + head1 + r" \\", r"Accuracy (\%) & " + head2 + r" \\", r"\midrule",
             rf"\multicolumn{{{ncols}}}{{@{{}}l}}{{\textit{{Named rules (best per model in bold)}}}} \\"]
    for k, lab in RULES:
        cells = []
        for m in cd.MODELS:
            c = pci(*res[m][k][:3])
            cells.append(rf"\textbf{{{c}}}" if res[m]["best"] == k else c)
        lines.append(f"{lab} & " + " & ".join(cells) + r" \\")
    lines += [r"\midrule", rf"\multicolumn{{{ncols}}}{{@{{}}l}}{{\textit{{Baselines and fitted policy}}}} \\",
              "Majority class & " + " & ".join(f"{pci(*res[m]['majority'][:3])}" for m in cd.MODELS) + r" \\",
              "Majority move & " + " & ".join(str(res[m]["maj_class"]) for m in cd.MODELS) + r" \\",
              "Tree, cross-validated & " + " & ".join(pci(*res[m]["tree"][:3]) for m in cd.MODELS) + r" \\",
              "Tree without risk $p$ & " + " & ".join(pci(*res[m]["treenop"][:3]) for m in cd.MODELS) + r" \\",
              "Change without $p$ (pp) & " + " & ".join(dci(*(100 * np.array(res[m]["dp"][:3])), digits=1)
                                                       for m in cd.MODELS) + r" \\",
              "Tree minus best rule (pp) & " + " & ".join(dci(*(100 * np.array(res[m]["gain"][:3])), digits=1)
                                                         for m in cd.MODELS) + r" \\",
              r"\midrule",
              "Games & " + " & ".join(str(res[m]["n_games"]) for m in cd.MODELS) + r" \\",
              "Decisions & " + " & ".join(f"{res[m]['n_dec']:,}".replace(",", "{,}") for m in cd.MODELS) + r" \\",
              r"\midrule",
              note("Accuracy is the share of a model's decisions a policy predicts exactly, with a 95\\% bootstrap "
                   "interval over games; base-prompt games (self-play, mixed tables, scripted partners). "
                   "Always 2. Repeat own move: last round's own move, 2 in round 1. Copy the group: the others' "
                   "mean last round rounded to 0, 2 or 4, 2 in round 1. Last-round skipper: 2, then 0 in round 10. "
                   "Stop when settled: 2 until the target is reached or out of reach, then 0. Pool tracker: 0 once "
                   "settled, else the share each seat still needs per round rounded up to 2 or 4. Risk-neutral "
                   "step: 0 at $p<0.5$; at $p\\ge 0.5$, 2 until the target is reached, then 0. Tree: depth 5, at "
                   "least 50 decisions per leaf, five folds that keep each game in one fold; features are the own "
                   "previous move, the others' previous mean, the pool against the fair pace, rounds left, a "
                   "last-round flag, reached, out of reach, the amount each seat still needs per round, and $p$. "
                   "Changes are paired over the same decisions.", ncols, 0.72),
              r"\bottomrule", r"\end{tabular}"]
    write_tabular("s_strat_rules.tex", lines)
    return res, drop_max


# ============================================================================ C. Grok opening
PARTNERS = ("Haiku", "Flash-Lite", "Luna", "Qwen")
OUTCOMES = (("total", "Total, rounds 2 to 10"), ("before", "Per round, pool below 120"),
            ("after", "Per round, pool at 120 or more"))


def fe_coef(y, x, own, cell):
    ok = np.isfinite(y)
    y, x, own, cell = y[ok], x[ok], own[ok], cell[ok]
    _, c = np.unique(cell, return_inverse=True)
    cnt = np.bincount(c)

    def dm(v):
        return v - (np.bincount(c, weights=v) / cnt)[c]
    A = np.column_stack([dm(x), dm(own)])
    if np.allclose(A[:, 1], 0) or np.linalg.matrix_rank(A) < 2:
        A = A[:, :1]
    return float(np.linalg.lstsq(A, dm(y), rcond=None)[0][0])


def opening(mg):
    rows = []
    for g in mg.itertuples():
        names = [cd.SLUG[s] for s in g.llm]
        if "Grok" not in names:
            continue
        m = next(n for n in names if n != "Grok")
        gi = [i for i, n in enumerate(names) if n == "Grok"]
        mi = [i for i, n in enumerate(names) if n == m]
        pot_start = np.r_[0.0, np.cumsum(g.strat.sum(axis=0))[:-1]]
        before = [t for t in range(1, cd.N_ROUNDS) if pot_start[t] < cd.TARGET]
        after = [t for t in range(1, cd.N_ROUNDS) if pot_start[t] >= cd.TARGET]
        rows.append(dict(gid=g.gid, model=m, kG=len(gi), p=round(g.p, 3),
                         grok_open=g.strat[gi, 0].mean(), own_open=g.strat[mi, 0].mean(),
                         total=g.strat[mi, 1:].sum(axis=1).mean(),
                         before=g.strat[np.ix_(mi, before)].mean() if before else np.nan,
                         after=g.strat[np.ix_(mi, after)].mean() if after else np.nan))
    O = pd.DataFrame(rows)
    res = {}
    print("\n[C] effect of +1 unit of mean Grok opening move on the partner (cell FE, own opening control)")
    for mi, m in enumerate(PARTNERS):
        x = O[O.model == m].reset_index(drop=True)
        if len(x) != 150 or x.groupby(["kG", "p"]).size().nunique() != 1:
            raise RuntimeError(f"{m}: {len(x)} games beside Grok, cells unbalanced")
        cell = (x.kG.astype(str) + "_" + x.p.astype(str)).to_numpy()
        cells = [np.flatnonzero(cell == c) for c in np.unique(cell)]
        go, oo = x.grok_open.to_numpy(float), x.own_open.to_numpy(float)
        sd = float(np.std(go - pd.Series(go).groupby(cell).transform("mean").to_numpy(), ddof=1))
        for oi, (k, _) in enumerate(OUTCOMES):
            y = x[k].to_numpy(float)
            est = fe_coef(y, go, oo, cell)
            g = np.random.default_rng(cd.SEED + 3000 + 10 * mi + oi)
            draws = np.empty(N_BOOT)
            for b in range(N_BOOT):
                pick = np.concatenate([c[g.integers(0, len(c), len(c))] for c in cells])
                draws[b] = fe_coef(y[pick], go[pick], oo[pick], cell[pick])
            res[(m, k)] = (est, float(np.percentile(draws, 2.5)), float(np.percentile(draws, 97.5)),
                           int(np.isfinite(y).sum()))
        res[(m, "sd")] = sd
        print(f"  {m:10} within-cell sd of Grok opening {sd:.2f} | " + " | ".join(
            f"{k} {res[(m, k)][0]:+.3f} [{res[(m, k)][1]:+.3f},{res[(m, k)][2]:+.3f}] n={res[(m, k)][3]}"
            for k, _ in OUTCOMES))

    def covers0(m):
        return res[(m, "before")][1] <= 0 <= res[(m, "before")][2]
    # Flash-Lite's interval excludes 0 (as it already did in the exploration), so the guard
    # asserts what the data support: a small effect, entirely above Luna's interval.
    problems = [] if covers0("Haiku") else ["Haiku before-reached CI excludes 0"]
    if not res[("Luna", "before")][2] < 0:
        problems.append("Luna before-reached CI no longer below 0")
    fl = res[("Flash-Lite", "before")]
    if abs(fl[0]) > 0.05 or not fl[1] > res[("Luna", "before")][2]:
        problems.append(f"Flash-Lite before-reached effect {fl[0]:+.3f} is no longer small and above Luna's CI")
    guard("Luna before-reached effect x100", 100 * res[("Luna", "before")][0], -37, tol=5)
    if problems:
        raise RuntimeError("opening sign pattern changed: " + "; ".join(problems))

    ncols = 5
    lines = [r"\begin{tabular}{@{}lrccc@{}}", r"\toprule",
             r" & & \multicolumn{3}{c}{Partner's payment per seat} \\", r"\cmidrule(l){3-5}",
             "Partner model & Games & " + " & ".join(lab for _, lab in OUTCOMES) + r" \\", r"\midrule"]
    for m in PARTNERS:
        cells = [dci(*res[(m, k)][:3]) + (f" ({res[(m, k)][3]})" if k == "after" else "") for k, _ in OUTCOMES]
        lines.append(f"{cd.show(m)} & {res[(m, 'total')][3]} & " + " & ".join(cells) + r" \\")
    lines += [r"\midrule",
              note("Change in the partner's payment per seat for one more unit in the mean opening move of the "
                   f"{cd.show('Grok')} seats, which is made before any history. Mixed tables of {cd.show('Grok')} with one "
                   "other model; OLS within cells of the same number of Grok seats and the same $p$, controlling for the "
                   "partner's own opening move; 95\\% bootstrap interval resampling games within cells. Per-round columns "
                   "average rounds 2 to 10 whose starting pool is below 120, or at 120 or more; the last column counts "
                   "only games with such rounds (in brackets after the interval: games).", ncols, 0.84),
              r"\bottomrule", r"\end{tabular}"]
    write_tabular("s_strat_opening.tex", lines)
    return res


# ============================================================================ D. equilibrium
def equilibrium(games):
    g = games[games.exp == "exp_baseline"].copy()
    g["p"] = g.p.round(3)
    g["model"] = [cd.SLUG[l[0]] for l in g.llm]
    if not all(len(set(l)) == 1 for l in g.llm) or len(g) != 550:
        raise RuntimeError(f"exp_baseline is not 550 self-play games ({len(g)})")
    g = g[g.p < 1]
    g["worst"] = (1.0 - g.p) * cd.ENDOWMENT
    g["below"] = (g.exp_welfare < g.worst - 1e-9).astype(float)
    res = {}
    print("\n[D] share of self-play games with expected welfare per seat below the worst Nash equilibrium (1-p)40")
    for mi, m in enumerate(cd.MODELS):
        d = g[g.model == m]
        hi = d[d.p > 0.5]
        lo = d[d.p < 0.5]
        res[m] = dict(high=mean_boot(hi.below, 4000 + 10 * mi), low=mean_boot(lo.below, 4001 + 10 * mi),
                      w_high=hi.exp_welfare.mean(), worst_high=hi.worst.mean())
        r = res[m]
        print(f"  {m:10} p>0.5: {100 * r['high'][0]:5.1f}% [{100 * r['high'][1]:.0f},{100 * r['high'][2]:.0f}] "
              f"n={r['high'][3]} (welfare {r['w_high']:.1f} vs worst NE {r['worst_high']:.1f}) | "
              f"p<0.5: {100 * r['low'][0]:5.1f}% n={r['low'][3]}")
    for m, want in {"Qwen": 100, "Grok": 92, "Luna": 25, "Haiku": 0, "Flash-Lite": 0}.items():
        guard(f"below worst NE {m}", 100 * res[m]["high"][0], want)

    ncols = 5
    lines = [r"\begin{tabular}{@{}lrcrc@{}}", r"\toprule",
             r" & \multicolumn{2}{c}{$0.5<p<1$} & \multicolumn{2}{c}{$p<0.5$} \\",
             r"\cmidrule(l){2-3}\cmidrule(l){4-5}",
             r"Model & Games & Below (\%) & Games & Below (\%) \\", r"\midrule"]
    for m in cd.MODELS:
        r = res[m]
        lines.append(f"{cd.show(m)} & {r['high'][3]} & {pci(*r['high'][:3])} & {r['low'][3]} & {pci(*r['low'][:3])}" + r" \\")
    lines += [r"\midrule",
              note("Share of self-play games on the risk grid whose expected payoff per seat falls below that of the "
                   "worst Nash equilibrium, with a 95\\% bootstrap interval over games. By Proposition 1, for $p<1$ "
                   "the equilibria are $x=0$, worth $(1-p)40$ per seat, and profiles with $X=T$ and "
                   "$x_i\\le 40p$, which exist only for $p\\ge 0.5$ and are worth 20 per seat, never less than "
                   "$(1-p)40$. The worst equilibrium is therefore nobody pays, $(1-p)40$, at every $p<1$; below "
                   "$p=0.5$ it is also the only one. $p=1$ is left out because no payoff can fall below 0 there, "
                   "and $p=0.5$ because the two kinds of equilibrium tie.", ncols, 0.54),
              r"\bottomrule", r"\end{tabular}"]
    write_tabular("s_strat_equilibrium.tex", lines)
    return res


# ============================================================================ main
def main():
    t0 = time.time()
    games, _, _ = cd.build(BASE)
    counts = games.groupby("exp").size().to_dict()
    print("games per experiment:", counts)
    D = decisions(games)
    print(f"decisions: {len(D):,}")

    end, ahead, onpace = endgame(D, games)
    rul, drop_max = rules(D)
    opn = opening(games[games.exp == "exp_mixed"])
    eq = equilibrium(games)

    mac = cd.Macros("strategy.py")
    for m, st, name in (("Luna", "pivotal", "StratLunaZeroPivotal"), ("Luna", "slack", "StratLunaZeroSlack"),
                        ("Qwen", "pivotal", "StratQwenZeroPivotal"), ("Qwen", "slack", "StratQwenZeroSlack"),
                        ("Qwen", "reached", "StratQwenZeroReached"), ("Qwen", "late", "StratQwenZeroLateSafe"),
                        ("Haiku", "late", "StratHaikuZeroLateSafe"), ("Flash-Lite", "late", "StratFlashZeroLateSafe"),
                        ("Luna", "late", "StratLunaZeroLateSafe")):
        mac.add(name, pct(end[(m, st)][0]))
    mac.add("StratLunaAheadReach", pct(ahead[0]))
    mac.add("StratLunaAheadN", str(ahead[3]))
    mac.add("StratLunaOnPaceReach", pct(onpace[0]))
    mac.add("StratLunaOnPaceN", str(onpace[3]))

    mac.add("StratRiskDropMax", rnd(100 * max(drop_max, 0.0), 1))
    for m in cd.MODELS:
        mac.add(f"StratRuleBest{cd.MACRO[m]}", RULE_TEXT[rul[m]["best"]])
    mac.add("StratMajorityMin", pct(min(rul[m]["majority"][0] for m in cd.MODELS)))
    mac.add("StratTreeMin", pct(min(rul[m]["tree"][0] for m in cd.MODELS)))
    mac.add("StratTreeMax", pct(max(rul[m]["tree"][0] for m in cd.MODELS)))

    for m in PARTNERS:
        e, lo, hi, _ = opn[(m, "before")]
        mac.add(f"StratOpen{cd.MACRO[m]}Before", rnd(e, 2))
        mac.add(f"StratOpen{cd.MACRO[m]}BeforeLo", rnd(lo, 2))
        mac.add(f"StratOpen{cd.MACRO[m]}BeforeHi", rnd(hi, 2))
        mac.add(f"StratOpen{cd.MACRO[m]}Total", rnd(opn[(m, "total")][0], 1))

    for m in ("Qwen", "Grok", "Luna", "Haiku", "Flash-Lite"):
        mac.add(f"StratBelowWorst{cd.MACRO[m]}", pct(eq[m]["high"][0]))
    path = mac.write("num_strategy.tex")
    print(f"\nwrote {path.relative_to(cd.REPO)}")
    for k, v in mac.items.items():
        print(f"  \\{k} = {v}")
    print(f"runtime {time.time() - t0:.1f} s")


if __name__ == "__main__":
    main()
