"""Supplementary tables (and one figure) for the in-game questions.

Run from the repository root:
    python paper/AAMAS/analysis/supp_probes.py

Reads results/exp_evprobe and results/exp_evprobe_probes.csv (read-only) through
crsd_data and probes (load, decode_value_compare, shifts). Never calls probes.main() or
probes.figure(), which rewrite the paper's own figure and macros.

Writes, into paper/AAMAS/supplement/tables/:
    s_probe_rules.tex   accuracy per rule question x model, with n per cell
    s_probe_value.tex   value comparison: A / B / equal counts and % correct, model x p
    s_probe_rounds.tex  share saying keeping pays more, model x p x round; games that change
    s_probe_defect.tex  second value question: % correct (by round), 40, cash-left reading, 0, other
    s_knowdo.tex        numbers behind the know-do scatter: levels and shifts with 95% CIs
and paper/AAMAS/supplement/figures/sfig_answers.pdf (+ .png).

Every value printed here that the paper also carries as a macro in
paper/AAMAS/tables/num_probes.tex is compared with that macro, and a mismatch raises.

Statistics: unit = game. Level CIs are 95% percentile bootstraps over the ten games of a
cell (offsets 6000+); shift CIs are exactly probes.shifts() (offsets 900+).
"""
from __future__ import annotations

import ast
import pathlib
import re
import sys
from decimal import ROUND_HALF_UP, Decimal

import numpy as np
import pandas as pd

HERE = pathlib.Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

import crsd_data as cd  # noqa: E402
import probes as pr  # noqa: E402

SOURCE = "paper/AAMAS/analysis/supp_probes.py"
SUPP = cd.PAPER / "supplement"
OUT = SUPP / "tables"
FIGS = SUPP / "figures"
MACRO_FILE = cd.TABLES / "num_probes.tex"

RISKS = pr.RISKS
ROUNDS = pr.ROUNDS
N_PER_CELL = 10                     # games per model per risk level

# Question order = the order of the program's question registry (asserted in
# make_questions.py). Labels are the only names a reader sees.
RULES = ["rules_actions", "rules_endowment", "rules_target", "rules_n_rounds",
         "rules_risk_pct", "rules_payoff_disaster", "rules_max_contrib", "rules_min_contrib"]
VALUES = ["value_defect_ev", "value_compare"]
QUESTIONS = RULES + VALUES
LABELS = {
    "rules_actions": "Allowed amounts",
    "rules_endowment": "Starting endowment",
    "rules_target": "Group target",
    "rules_n_rounds": "Number of rounds",
    "rules_risk_pct": "Disaster probability",
    "rules_payoff_disaster": "Payoff after disaster",
    "rules_max_contrib": "Largest payment",
    "rules_min_contrib": "Smallest payment",
    "value_defect_ev": "Expected cash from paying nothing",
    "value_compare": "Two strategies compared",
}
ANSWER_NAME = {pr.ANS_FAIR: "A", pr.ANS_KEEP: "B", pr.ANS_EQUAL: "Equal"}


# ------------------------------------------------------------------ formatting
def half_up(x: float, digits: int = 0) -> str:
    """Decimal rounding, half away from zero, on the shortest repr of the float."""
    q = Decimal(1).scaleb(-digits)
    d = Decimal(repr(float(x))).quantize(q, rounding=ROUND_HALF_UP)
    s = f"{d:f}"
    if d == 0:
        s = s.lstrip("-")
    return s


def num(x: float, digits: int = 1) -> str:
    s = half_up(x, digits)
    return "$-$" + s[1:] if s.startswith("-") else s


def pct_kn(k: int, n: int) -> str:
    """k of n as a whole percent, exact half-up."""
    k, n = int(k), int(n)
    val = (200 * k + n) // (2 * n)
    s = str(val)
    if s != pr.pct0(k / n):
        raise AssertionError(f"percent rounding disagrees for {k}/{n}")
    return s


def thousands(n: int) -> str:
    return pr.thousands(n)


def ptex(p: float) -> str:
    return f"$p={p:g}$"


def ci(lo: float, hi: float, digits: int) -> str:
    return f"[{num(lo, digits)}, {num(hi, digits)}]"


def model_header(models=cd.MODELS) -> tuple[str, str]:
    """Two header rows that print each model's full name over two lines."""
    top = " & ".join(cd.LINES[m][0] for m in models)
    bottom = " & ".join(cd.LINES[m][1] for m in models)
    if any(cd.show(m) not in (f"{cd.LINES[m][0]} {cd.LINES[m][1]}",
                              f"{cd.LINES[m][0]}-{cd.LINES[m][1]}") for m in models):
        raise AssertionError("two-line model names do not join to the display names")
    return top, bottom


def write_tabular(name: str, body: list[str]) -> pathlib.Path:
    OUT.mkdir(parents=True, exist_ok=True)
    text = "\n".join([f"% Generated by {SOURCE}. Do not edit by hand."] + body) + "\n"
    lint(text, name)
    path = OUT / name
    path.write_text(text, encoding="utf-8")
    return path


def lint(text: str, name: str) -> None:
    """Reader-facing rules: no dashes that render as en or em dash, no internal codes,
    no question ids, and every model named with family and version."""
    if not text.startswith("% Generated by"):
        raise AssertionError(f"{name}: missing generated-by header")
    text = text.split("\n", 1)[1]          # the header names this script's file
    for bad in ("--", "\u2013", "\u2014", "exp_", "evprobe", "_probes", ".csv"):
        if bad in text:
            raise AssertionError(f"{name}: forbidden text {bad!r}")
    for qid in QUESTIONS:
        if qid in text:
            raise AssertionError(f"{name}: question id {qid} in reader-facing output")
    top, bottom = model_header()
    stripped = text.replace(top, "").replace(bottom, "")
    for m in cd.MODELS:
        stripped = stripped.replace(cd.show(m), "")
    for nick in ("Luna", "Qwen", "Grok", "Haiku", "Flash-Lite", "Gemini", "Claude", "GPT"):
        if re.search(rf"\b{re.escape(nick)}\b", stripped):
            raise AssertionError(f"{name}: model named without family and version ({nick!r})")


# ------------------------------------------------------------------ consistency gate
def read_macros() -> dict[str, str]:
    out = {}
    for line in MACRO_FILE.read_text(encoding="utf-8").splitlines():
        m = re.fullmatch(r"\\newcommand\{\\([A-Za-z]+)\}\{(.*)\}", line.strip())
        if m:
            out[m.group(1)] = m.group(2)
    if not out:
        raise RuntimeError(f"no macros parsed from {MACRO_FILE}")
    return out


class Gate:
    """Values this script prints (or derives from what it prints) that the paper also
    carries as macros. check() raises RuntimeError on any difference."""

    def __init__(self):
        self.macros = read_macros()
        self.seen: dict[str, str] = {}

    def add(self, name: str, value: str) -> None:
        if name not in self.macros:
            raise RuntimeError(f"gate names a macro that num_probes.tex lacks: {name}")
        if name in self.seen and self.seen[name] != value:
            raise RuntimeError(f"gate value for {name} set twice: {self.seen[name]} vs {value}")
        self.seen[name] = value

    def check(self) -> None:
        bad = [(k, v, self.macros[k]) for k, v in self.seen.items() if self.macros[k] != v]
        if bad:
            raise RuntimeError("supplement disagrees with num_probes.tex: "
                               + "; ".join(f"\\{k}: table {v!r} vs macro {m!r}" for k, v, m in bad))
        print(f"consistency gate: {len(self.seen)} values agree with num_probes.tex "
              f"({', '.join(sorted(self.seen))})")


# ------------------------------------------------------------------ data
def load():
    g, probes = pr.load()
    if len(g) != 150 or len(probes) != 4500:
        raise AssertionError(f"expected 150 games and 4500 answers, got {len(g)} / {len(probes)}")
    if set(probes["question_id"]) != set(QUESTIONS):
        raise AssertionError(f"question ids {sorted(set(probes['question_id']))}")
    if probes["parse_failed"].any():
        raise AssertionError("parse failures present in the answers")
    cats = probes.groupby("question_id")["category"].unique()
    for q in QUESTIONS:
        want = "rules" if q in RULES else "value"
        if list(cats[q]) != [want]:
            raise AssertionError(f"{q}: category {list(cats[q])}")
    cells = probes.groupby(["model", "p", "round", "question_id"]).size()
    if not (cells == N_PER_CELL).all() or len(cells) != 5 * 3 * 3 * 10:
        raise AssertionError("expected ten answers per model x p x round x question")
    vc = pr.decode_value_compare(probes)
    vc["keep"] = (vc["ans"] == pr.ANS_KEEP).astype(float)
    return g, probes, vc


# ------------------------------------------------------------------ tables
def table_rules(probes: pd.DataFrame, gate: Gate) -> pathlib.Path:
    rules = probes[probes["category"] == "rules"]
    top, bottom = model_header()
    cols = len(cd.MODELS) + 1
    body = [f"\\begin{{tabular}}{{@{{}}l{'r' * cols}@{{}}}}", "\\toprule",
            f"Question & {top} & All \\\\",
            f" & {bottom} & models \\\\",
            "\\midrule"]

    def cell(frame):
        k, n = int(frame["correct"].sum()), len(frame)
        return f"{pct_kn(k, n)} ({thousands(n)})", k, n

    for q in RULES:
        row = [LABELS[q]]
        for m in cd.MODELS:
            row.append(cell(rules[(rules["question_id"] == q) & (rules["model"] == m)])[0])
        row.append(cell(rules[rules["question_id"] == q])[0])
        body.append(" & ".join(row) + " \\\\")
    body.append("\\midrule")
    row = ["All rule questions"]
    for m in cd.MODELS:
        row.append(cell(rules[rules["model"] == m])[0])
    text, k, n = cell(rules)
    row.append(text)
    body += [" & ".join(row) + " \\\\", "\\bottomrule", "\\end{tabular}"]
    gate.add("ProbeRulePct", pct_kn(k, n))
    gate.add("ProbeRuleQuestions", thousands(n))
    gate.add("ProbeQuestions", thousands(len(probes)))
    gate.add("ProbeValueQuestions", thousands(int((probes["category"] == "value").sum())))
    gate.add("ProbeGames", str(probes["gid"].nunique()))
    return write_tabular("s_probe_rules.tex", body)


def table_value(vc: pd.DataFrame, gate: Gate) -> pathlib.Path:
    gt = vc.groupby("p")["gt"].unique()
    body = ["\\begin{tabular}{@{}llcrrrr@{}}", "\\toprule",
            " & & Correct & \\multicolumn{3}{c}{Answers saying} & Correct \\\\",
            "\\cmidrule(lr){4-6}",
            "Model & Risk & answer & A higher & B higher & Equal & (\\%) \\\\",
            "\\midrule"]
    for i, m in enumerate(cd.MODELS):
        if i:
            body.append("\\addlinespace")
        mv = vc[vc["model"] == m]
        for j, p in enumerate(RISKS):
            cell = mv[mv["p"] == p]
            if len(cell) != 3 * N_PER_CELL:
                raise AssertionError(f"{m} p={p}: {len(cell)} answers")
            counts = cell["ans"].value_counts()
            want = int(gt[p][0])
            row = [cd.show(m) if j == 0 else "", ptex(p), ANSWER_NAME[want]]
            row += [str(int(counts.get(a, 0))) for a in (pr.ANS_FAIR, pr.ANS_KEEP, pr.ANS_EQUAL)]
            row.append(pct_kn(int(cell["correct"].sum()), len(cell)))
            body.append(" & ".join(row) + " \\\\")
        counts = mv["ans"].value_counts()
        row = ["", "All", ""]
        row += [str(int(counts.get(a, 0))) for a in (pr.ANS_FAIR, pr.ANS_KEEP, pr.ANS_EQUAL)]
        overall = pct_kn(int(mv["correct"].sum()), len(mv))
        row.append(overall)
        body.append(" & ".join(row) + " \\\\")
        gate.add(f"ProbeCorrect{cd.MACRO[m]}Pct", overall)
        if len(mv) != 9 * N_PER_CELL:
            raise AssertionError(f"{m}: {len(mv)} value-comparison answers")
    body += ["\\bottomrule", "\\end{tabular}"]
    q = vc[vc["model"] == "Qwen"]
    gate.add("ProbeQwenKeepPct", pct_kn(int(q["keep"].sum()), len(q)))
    return write_tabular("s_probe_value.tex", body)


def switched_games(vc: pd.DataFrame) -> pd.Series:
    wide = vc.pivot_table(index=["model", "p", "gid"], columns="round", values="ans")
    if wide.isna().any().any() or list(wide.columns) != list(ROUNDS):
        raise AssertionError("a game lacks one of its three value-comparison answers")
    return wide.nunique(axis=1) > 1


def table_rounds(vc: pd.DataFrame, gate: Gate) -> pathlib.Path:
    sw = switched_games(vc)
    body = [f"\\begin{{tabular}}{{@{{}}l{'r' * 9}{'r' * 4}@{{}}}}", "\\toprule",
            " & \\multicolumn{9}{c}{Answers saying B (paying nothing) is higher (\\%)}"
            " & \\multicolumn{4}{c}{Games whose answer changes} \\\\",
            "\\cmidrule(lr){2-10}\\cmidrule(l){11-14}",
            " & " + " & ".join(f"\\multicolumn{{3}}{{c}}{{{ptex(p)}}}" for p in RISKS)
            + " & \\multicolumn{3}{c}{By $p$ (of 10)} & All \\\\",
            "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\\cmidrule(lr){8-10}\\cmidrule(lr){11-13}",
            "Model & " + " & ".join(" & ".join(f"R{r}" for r in ROUNDS) for _ in RISKS)
            + " & " + " & ".join(f"{p:g}" for p in RISKS) + " & (of 30) \\\\",
            "\\midrule"]
    for m in cd.MODELS:
        row = [cd.show(m)]
        for p in RISKS:
            for r in ROUNDS:
                cell = vc[(vc["model"] == m) & (vc["p"] == p) & (vc["round"] == r)]
                if len(cell) != N_PER_CELL:
                    raise AssertionError(f"{m} p={p} round {r}: {len(cell)} answers")
                row.append(pct_kn(int(cell["keep"].sum()), len(cell)))
        per_p = [int(sw.loc[(m, p)].sum()) for p in RISKS]
        if any(len(sw.loc[(m, p)]) != N_PER_CELL for p in RISKS):
            raise AssertionError(f"{m}: expected ten games per risk level")
        row += [str(k) for k in per_p] + [str(sum(per_p))]
        body.append(" & ".join(row) + " \\\\")
        if m == "Luna":
            gate.add("ProbeLunaSwitchGames", str(sum(per_p)))
    body += ["\\bottomrule", "\\end{tabular}"]
    # derived from the printed cells: Grok's round-1 cells, the three answering models at p=0.1
    grok1 = vc[(vc["model"] == "Grok") & (vc["round"] == 1)]
    gate.add("ProbeGrokRoundOneKeepPct", pct_kn(int(grok1["keep"].sum()), len(grok1)))
    low = vc[vc["model"].isin(pr.THREE) & (vc["p"] == 0.1) & vc["round"].isin([1, 5])]
    gate.add("ProbeThreeLowKeepPct", pct_kn(int(low["keep"].sum()), len(low)))
    return write_tabular("s_probe_rounds.tex", body)


def defect_readings(probes: pd.DataFrame, g: pd.DataFrame) -> pd.DataFrame:
    """Classify each answer to the second value question, in this order:
    correct; 40 (the endowment kept if the disaster does not strike); 0 (the cash left
    if it does); the expected value of what the seat has LEFT when asked,
    (1 - p) x (40 - its payments before that round), half-up to a whole number; other."""
    de = probes[probes["question_id"] == "value_defect_ev"].copy()
    de["ans"] = de["parsed_answer"].astype(int)
    de["gt"] = de["ground_truth"].astype(int)
    for p, gts in de.groupby("p")["gt"]:
        want = int(Decimal(repr((1.0 - p) * cd.ENDOWMENT)).quantize(Decimal(1), ROUND_HALF_UP))
        if set(gts) != {want}:
            raise AssertionError(f"p={p}: ground truth {set(gts)} but arithmetic says {want}")
    if not (de["correct"] == (de["ans"] == de["gt"])).all():
        raise AssertionError("'correct' disagrees with answer == ground truth")
    left = [cd.ENDOWMENT - float(g.loc[gid, "strat"][0][: r - 1].sum())
            for gid, r in zip(de["gid"], de["round"])]
    de["left"] = left
    de["left_ev"] = [int(Decimal(repr((1.0 - p) * x)).quantize(Decimal(1), ROUND_HALF_UP))
                     for p, x in zip(de["p"], de["left"])]
    if ((de["round"] == 1) & (de["left"] != cd.ENDOWMENT)).any():
        raise AssertionError("a seat has paid something before round 1")
    kind = np.full(len(de), "other", dtype=object)
    wrong = ~de["correct"].to_numpy()
    ans = de["ans"].to_numpy()
    left_ev = de["left_ev"].to_numpy()
    kind[~wrong] = "correct"
    kind[wrong & (ans == 40)] = "forty"
    kind[wrong & (ans == 0)] = "zero"
    lefts = wrong & (ans != 40) & (ans != 0) & (ans == left_ev)
    kind[lefts] = "left"
    if (wrong & ((ans == 0) | (ans == 40)) & (ans == left_ev)).any():
        raise AssertionError("an answer of 0 or 40 also equals the cash-left reading; "
                             "the categories overlap")
    de["kind"] = kind
    return de


def table_defect(de: pd.DataFrame) -> pathlib.Path:
    body = ["\\begin{tabular}{@{}llcrrrrrrrr@{}}", "\\toprule",
            " & & Correct & \\multicolumn{4}{c}{Correct (\\%)}"
            " & \\multicolumn{4}{c}{Wrong answers (\\% of all answers)} \\\\",
            "\\cmidrule(lr){4-7}\\cmidrule(l){8-11}",
            "Model & Risk & answer & All & R1 & R5 & R10 & 40 & 0 & Cash left & Other \\\\",
            "\\midrule"]
    for i, m in enumerate(cd.MODELS):
        if i:
            body.append("\\addlinespace")
        for j, p in enumerate(RISKS):
            cell = de[(de["model"] == m) & (de["p"] == p)]
            n = len(cell)
            if n != 3 * N_PER_CELL:
                raise AssertionError(f"{m} p={p}: {n} answers")
            row = [cd.show(m) if j == 0 else "", ptex(p), str(int(cell["gt"].iloc[0])),
                   pct_kn(int(cell["correct"].sum()), n)]
            for r in ROUNDS:
                c = cell[cell["round"] == r]
                row.append(pct_kn(int(c["correct"].sum()), len(c)))
            for k in ("forty", "zero", "left", "other"):
                row.append(pct_kn(int((cell["kind"] == k).sum()), n))
            body.append(" & ".join(row) + " \\\\")
    body += ["\\bottomrule", "\\end{tabular}"]
    return write_tabular("s_probe_defect.tex", body)


def table_knowdo(vc: pd.DataFrame, g: pd.DataFrame, gate: Gate) -> pathlib.Path:
    shifts = pr.shifts(vc, g).set_index("model")
    body = ["\\begin{tabular}{@{}llrlrl@{}}", "\\toprule",
            " & & \\multicolumn{2}{c}{Share saying B (paying nothing) is higher}"
            " & \\multicolumn{2}{c}{Units seat 1 pays} \\\\",
            "\\cmidrule(lr){3-4}\\cmidrule(l){5-6}",
            "Model & Risk & Mean & 95\\% CI & Mean & 95\\% CI \\\\",
            "\\midrule"]
    level = {}
    for i, m in enumerate(cd.MODELS):
        if i:
            body.append("\\addlinespace")
        for j, p in enumerate(RISKS):
            share = vc[(vc["model"] == m) & (vc["p"] == p)].groupby("gid")["keep"].mean()
            paid = g[(g["model"] == m) & (g["p"] == p)]["p1_total"].astype(float)
            if len(share) != N_PER_CELL or len(paid) != N_PER_CELL:
                raise AssertionError(f"{m} p={p}: {len(share)} answered / {len(paid)} games")
            if set(share.index) != set(paid.index):
                raise AssertionError(f"{m} p={p}: answered games differ from played games")
            k = cd.MODELS.index(m)
            s_lo, s_hi = cd.boot_ci(share.to_numpy(), offset=6000 + 10 * j + k)
            t_lo, t_hi = cd.boot_ci(paid.to_numpy(), offset=6100 + 10 * j + k)
            level[(m, p)] = paid.mean()
            body.append(" & ".join([cd.show(m) if j == 0 else "", ptex(p),
                                    num(share.mean(), 2), ci(s_lo, s_hi, 2),
                                    num(paid.mean(), 1), ci(t_lo, t_hi, 1)]) + " \\\\")
        d = shifts.loc[m]
        body.append(" & ".join(["", "Shift", num(d["dx"], 2), ci(d["x_lo"], d["x_hi"], 2),
                                num(d["dy"], 1), ci(d["y_lo"], d["y_hi"], 1)]) + " \\\\")
    body += ["\\bottomrule", "\\end{tabular}"]
    # derived: the three answering models pooled (ten games each, so the pooled mean is
    # the mean of the per-model means)
    lo = np.mean([level[(m, 0.1)] for m in pr.THREE])
    hi = np.mean([level[(m, 0.9)] for m in pr.THREE])
    gate.add("ProbeThreeLowContrib", cd.fmt(lo))
    gate.add("ProbeThreeHighContrib", cd.fmt(hi))
    gate.add("ProbeThreeRiskShift", cd.fmt(hi - lo))
    if abs(np.mean([shifts.loc[m, "dy"] for m in pr.THREE]) - (hi - lo)) > 1e-9:
        raise AssertionError("pooled shift differs from the mean of the per-model shifts")
    return write_tabular("s_knowdo.tex", body)


# ------------------------------------------------------------------ figure
def figure(vc: pd.DataFrame) -> pathlib.Path:
    """Stacked bars of the three answers, one panel per model, bars grouped by risk
    level with one bar per question round. Colours follow the paper's meaning table for
    units paid: the answer favouring paying nothing takes the colour of 0, the answer
    favouring paying 2 takes the colour of 2; a tie is neutral grey."""
    import crsd_style as cs
    from matplotlib.patches import Patch

    cs.use()
    fig, axes = cs.subplots("full", height_pt=128, ncols=len(cd.MODELS), sharey=True)
    parts = [(pr.ANS_KEEP, cs.PAY_COLOURS[0], "B higher (pay nothing)"),
             (pr.ANS_EQUAL, cs.LINE, "Equal"),
             (pr.ANS_FAIR, cs.PAY_COLOURS[2], "A higher (pay 2 each round)")]
    width, gap = 0.8, 0.9
    for ax, m in zip(axes, cd.MODELS):
        xs, ticks, groups = [], [], []
        for j, p in enumerate(RISKS):
            base = j * (len(ROUNDS) + gap)
            groups.append((base + (len(ROUNDS) - 1) / 2, p))
            for i, r in enumerate(ROUNDS):
                x = base + i
                cell = vc[(vc["model"] == m) & (vc["p"] == p) & (vc["round"] == r)]["ans"]
                bottom = 0.0
                for code, colour, _ in parts:
                    h = float((cell == code).mean())
                    if h > 0:
                        ax.bar(x, h, width=width, bottom=bottom, color=colour,
                               edgecolor=cs.WHITE, linewidth=0.4, zorder=2)
                    bottom += h
                if abs(bottom - 1.0) > 1e-9:
                    raise AssertionError(f"{m} p={p} round {r}: shares sum to {bottom}")
                xs.append(x)
                ticks.append(str(r))
        ax.set_xticks(xs, ticks)
        ax.tick_params(axis="x", length=0, pad=1.5)
        ax.set_xlim(-0.6, xs[-1] + 0.6)
        ax.set_ylim(0, 1)
        ax.set_yticks([0, 0.5, 1], ["0", "0.5", "1"])
        ax.grid(False)
        ax.spines["bottom"].set_visible(False)
        ax.set_title(cd.show(m), loc="center", fontsize=cs.SIZE_LABEL, fontweight="normal",
                     color=cs.model(m).text)
        for xc, p in groups:
            ax.annotate(f"p = {p:g}", (xc, 0), xycoords=("data", "axes fraction"),
                        xytext=(0, -11), textcoords="offset points", ha="center", va="top",
                        fontsize=cs.SIZE_SMALL, color=cs.MUTED, annotation_clip=False)
    axes[0].set_ylabel("Share of answers")
    fig.supxlabel("Question round, by catastrophe probability", fontsize=cs.SIZE_LABEL)
    handles = [Patch(facecolor=c, edgecolor=cs.WHITE if c != cs.PAY_COLOURS[0] else cs.LINE,
                     linewidth=0.4, label=lab) for _, c, lab in parts]
    cs.legend_top(fig, handles, ncols=3, handlelength=1.0, handleheight=0.8)
    return cs.save(fig, FIGS / "sfig_answers", width="full", title="sfig_answers")


# ------------------------------------------------------------------ main
def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    g, probes, vc = load()
    gate = Gate()
    paths = [table_rules(probes, gate), table_value(vc, gate), table_rounds(vc, gate)]
    de = defect_readings(probes, g)
    paths.append(table_defect(de))
    paths.append(table_knowdo(vc, g, gate))
    gate.check()
    for path in paths:
        print(f"wrote {path.relative_to(cd.REPO)}")

    # console summary for the report (not written anywhere)
    print("\nsecond value question, answer kinds by model x round:")
    print(de.groupby(["model", "round"])["kind"].value_counts().unstack(fill_value=0)
          .reindex(columns=["correct", "forty", "zero", "left", "other"], fill_value=0).to_string())
    print("pooled:", de["kind"].value_counts().to_dict(), "of", len(de))
    sw = switched_games(vc)
    print("games whose comparison answer changes:", sw.groupby(level="model").sum().to_dict())
    by_round = vc.groupby(["model", "round"])["correct"].mean().unstack().round(3)
    print("value comparison % correct by round:\n", by_round.to_string())

    pdf = figure(vc)
    print(f"wrote {pdf.relative_to(cd.REPO)} (+ .png)")


if __name__ == "__main__":
    main()
