"""Supplement: one model in seat 1 beside five scripted partners of one kind.

Run from the repository root:
    python paper/AAMAS/analysis/supp_scripted.py

Design: 4 partner kinds (always 0, always 2, always 4, copy the group) x 5 models x
p in {0.1, 0.3, 0.5, 0.7, 0.9} x 10 games = 1,000 games. Seat 1 is the model.

Reuses scripted.py (replay, brute force over all 3^10 own-move sequences, per-game frame,
two-way variance decomposition) by import. Never calls scripted.main() or
scripted.figure(), which rewrite the paper's own tables, macros and figure.

Writes ONLY
    paper/AAMAS/supplement/tables/s_scr_{best,totals,outcomes,variance,settled,grok,fair,free}.tex
    paper/AAMAS/supplement/tables/snum_scripted.tex
    paper/AAMAS/supplement/figures/sfig_scripted_rounds.pdf (+ .png)

Statistics: unit = game; payoffs are EXPECTED over the catastrophe lottery; intervals are
95% percentile bootstraps over games (cd.boot_ci, fixed offsets from 7000 up). Rounding
is half-up throughout.

Consistency gate: every printed value that the paper already quotes (tables/num_scripted.tex
and tables/tab_settled.tex) is compared string for string; any difference raises.
"""
from __future__ import annotations

import itertools
import re
import sys
from collections import Counter
from decimal import ROUND_HALF_UP, Decimal

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

import crsd_data as cd
import crsd_style as cs
import scripted as sc

SOURCE = "paper/AAMAS/analysis/supp_scripted.py"
HEADER = f"% Generated by {SOURCE}. Do not edit by hand."
SUPP = cd.PAPER / "supplement"
OUT_T = SUPP / "tables"
OUT_F = SUPP / "figures"

KINDS = ("all0", "all2", "all4", "cond")
KIND_NAME = {"all0": "Always 0", "all2": "Always 2", "all4": "Always 4", "cond": "Copy the group"}
RISKS = sc.RISKS
R = cd.N_ROUNDS
T = int(cd.TARGET)
MAX_ROWS = 45

# bootstrap offsets (fixed, >= 7000, one block per table)
OFF_OUTCOMES = 7000
OFF_SETTLED = 7100   # s_scr_free reuses OFF_OUTCOMES: its sample is the always-0 gap


# ------------------------------------------------------------------ formatting
def rnd(x: float, digits: int = 1) -> str:
    """Half-up rounding; LaTeX minus; never prints -0."""
    q = Decimal(1).scaleb(-digits)
    v = Decimal(repr(round(float(x), 9))).quantize(q, rounding=ROUND_HALF_UP)
    if v == 0:
        v = abs(v)
    s = f"{v:.{digits}f}"
    return "$-$" + s[1:] if s.startswith("-") else s


def pct(x: float) -> str:
    return rnd(100.0 * x, 0)


def ci(lo: float, hi: float) -> str:
    return f"[{rnd(lo)}, {rnd(hi)}]"


def seq(moves) -> str:
    return r"\,".join(str(int(a)) for a in moves)


def ptxt(p: float) -> str:
    return f"{p:g}"


FORBIDDEN = re.compile(r"--|\u2013|\u2014|all0|all2|all4|\bcond\b|exp_|scripted:|Legacy")


def write_tabular(name: str, lines) -> None:
    body = "\n".join(lines)
    bad = FORBIDDEN.search(body)
    if bad:
        raise RuntimeError(f"{name}: forbidden text {bad.group(0)!r}")
    if not (body.lstrip().startswith(r"\begin{tabular}") and body.rstrip().endswith(r"\end{tabular}")):
        raise RuntimeError(f"{name}: must contain exactly one tabular and nothing else")
    rows = sum(1 for ln in lines if ln.rstrip().endswith(r"\\"))
    if rows > MAX_ROWS:
        raise RuntimeError(f"{name}: {rows} rows > {MAX_ROWS}")
    OUT_T.mkdir(parents=True, exist_ok=True)
    (OUT_T / name).write_text(HEADER + "\n" + body + "\n", encoding="utf-8")
    print(f"wrote {OUT_T / name} ({rows} rows)")


def block(label: str, ncols: int) -> str:
    return rf"\multicolumn{{{ncols}}}{{@{{}}l}}{{\textit{{{label}}}}} \\"


def modes(items):
    """All values tied for the highest count, sorted, with that count."""
    c = Counter(items)
    top = max(c.values())
    return sorted(k for k, v in c.items() if v == top), top


# ------------------------------------------------------------------ gate
class Gate:
    """Values printed here that the paper already quotes. Compared string for string."""

    def __init__(self):
        self.macros: dict = {}
        self.settled: dict = {}

    def macro(self, name: str, value: str) -> None:
        if name in self.macros and self.macros[name] != value:
            raise RuntimeError(f"gate: {name} set twice ({self.macros[name]} vs {value})")
        self.macros[name] = value

    def check(self) -> None:
        text = (cd.TABLES / "num_scripted.tex").read_text(encoding="utf-8")
        paper = dict(re.findall(r"^\\newcommand\{\\(\w+)\}\{(.*)\}\s*$", text, re.M))
        problems = []
        for k, v in self.macros.items():
            if k not in paper:
                problems.append(f"{k} not in num_scripted.tex")
            elif paper[k] != v:
                problems.append(f"{k}: paper {paper[k]!r}, supplement {v!r}")
        tab = (cd.TABLES / "tab_settled.tex").read_text(encoding="utf-8")
        seen = 0
        for m in cd.MODELS:
            row = re.search(rf"^{re.escape(cd.show(m))} & (.*?) \\\\\s*$", tab, re.M)
            if not row:
                problems.append(f"tab_settled.tex: no row for {cd.show(m)}")
                continue
            vals = [v.strip() for v in row.group(1).split("&")]
            mine = [self.settled[(m, k, w)] for k in ("all0", "all4") for w in ("before", "after")]
            seen += 1
            if vals != mine:
                problems.append(f"tab_settled {cd.show(m)}: paper {vals}, supplement {mine}")
        if problems:
            raise RuntimeError("consistency gate failed:\n  " + "\n  ".join(problems))
        print(f"consistency gate passed: {len(self.macros)} macros of num_scripted.tex and "
              f"{seen} rows of tab_settled.tex match")


# ------------------------------------------------------------------ tables
def t_best(reach, gate: Gate) -> dict:
    sc.verify_best_response(reach)
    best = {k: {p: sc.best_totals(reach[k], p) for p in RISKS} for k in KINDS}
    n = 6
    lines = [r"\begin{tabular}{@{}lccccc@{}}", r"\toprule",
             r" & \multicolumn{5}{c}{Risk $p$} \\", r"\cmidrule(l){2-6}",
             "Partners & " + " & ".join(ptxt(p) for p in RISKS) + r" \\", r"\midrule",
             block("Best-response total over ten rounds", n)]
    for k in KINDS:
        lines.append(f"{KIND_NAME[k]} & " + " & ".join(
            " or ".join(str(t) for t in best[k][p][0]) for p in RISKS) + r" \\")
    lines += [r"\midrule", block("Best expected payoff", n)]
    for k in KINDS:
        lines.append(f"{KIND_NAME[k]} & " + " & ".join(rnd(best[k][p][1]) for p in RISKS) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_tabular("s_scr_best.tex", lines)
    return best


def best_text(totals) -> str:
    return " or ".join(str(int(t)) for t in totals)


def t_totals(d: pd.DataFrame, best, gate: Gate) -> float:
    n = 8
    lines = [r"\begin{tabular}{@{}lrrrrrrr@{}}", r"\toprule",
             r" & \multicolumn{5}{c}{Risk $p$} & All & $p>0.5$ minus \\",
             r"\cmidrule(lr){2-6}",
             "Model & " + " & ".join(ptxt(p) for p in RISKS) + r" & risks & $p<0.5$ \\",
             r"\midrule"]
    fair_change = []
    for i, k in enumerate(KINDS):
        if i:
            lines.append(r"\midrule")
        lines.append(block(KIND_NAME[k], n))
        for m in cd.MODELS:
            w = d[(d.profile == k) & (d.model == m)]
            by = w.groupby("p")["total"].mean()
            if len(w) != 50 or list(by.index) != list(RISKS):
                raise AssertionError(f"{k} {m}: {len(w)} games")
            change = w[w.p > 0.5]["total"].mean() - w[w.p < 0.5]["total"].mean()
            if k in ("all2", "cond"):
                fair_change.append(abs(change))
            cells = [rnd(by[p]) for p in RISKS] + [rnd(w["total"].mean()), rnd(change)]
            lines.append(f"{cd.show(m)} & " + " & ".join(cells) + r" \\")
            if m == "Qwen" and k == "all0":
                gate.macro("ScrQwenDefectPay", cells[5])
            if m == "Qwen" and k == "all2":
                gate.macro("ScrQwenFairPay", cells[5])
        # best-response row: every combination of tied totals across risks
        opts = [best[k][p][0] for p in RISKS]
        combos = sorted({float(np.mean(c)) for c in _product(opts)})
        lo = [best[k][p][0] for p in RISKS if p < 0.5]
        hi = [best[k][p][0] for p in RISKS if p > 0.5]
        if any(len(o) != 1 for o in lo + hi):
            raise AssertionError("best response tied away from p = 0.5")
        br_change = np.mean([o[0] for o in hi]) - np.mean([o[0] for o in lo])
        cells = [best_text(o) for o in opts] + [" or ".join(f"{c:g}" for c in combos),
                                                f"{br_change:g}"]
        lines.append("Best response & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_tabular("s_scr_totals.tex", lines)
    return max(fair_change)


def _product(opts):
    return itertools.product(*opts)


def t_outcomes(d: pd.DataFrame, best, gate: Gate) -> None:
    n = 6
    lines = [r"\begin{tabular}{@{}lrrrlr@{}}", r"\toprule",
             r" & Reached & Expected & \multicolumn{2}{c}{Gap to best response} & Exactly optimal \\",
             r"\cmidrule(lr){4-5}",
             r"Model & (of 50) & payoff & Mean & 95\% CI & (of 50) \\", r"\midrule"]
    n_opt = 0
    opt_totals = set()
    for i, k in enumerate(KINDS):
        if i:
            lines.append(r"\midrule")
        lines.append(block(KIND_NAME[k], n))
        for j, m in enumerate(cd.MODELS):
            w = d[(d.profile == k) & (d.model == m)]
            lo, hi = cd.boot_ci(w["gap"], offset=OFF_OUTCOMES + 10 * i + j)
            opt = w[w["gap"].abs() < 1e-9]
            n_opt += len(opt)
            opt_totals.update(opt["total"].tolist())
            reached = int(w["reached"].sum())
            lines.append(f"{cd.show(m)} & {reached} & {rnd(w['exp_pay'].mean())} & "
                         f"{rnd(w['gap'].mean())} & {ci(lo, hi)} & {len(opt)}" + r" \\")
            if k == "all2" and m == "Flash-Lite":
                gate.macro("ScrFlashFairReach", str(reached))
            if k == "all2" and m == "Qwen":
                gate.macro("ScrQwenFairMiss", str(50 - reached))
        # best responder: payoff is unique; reaching the target is not at a tie
        pay = np.mean([best[k][p][1] for p in RISKS])
        reach_counts = sorted({sum(10 * int(t > 0 or k == "all4") for t in c)
                               for c in _product([best[k][p][0] for p in RISKS])})
        lines.append(f"Best response & {' or '.join(map(str, reach_counts))} & {rnd(pay)} & "
                     f"{rnd(0)} &  & 50" + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    gate.macro("ScrOptimalGames", str(n_opt))
    if opt_totals != {20}:
        raise AssertionError(f"exactly optimal games with totals {sorted(opt_totals)}")
    gate.macro("ScrOptimalAllTwenty", "every")
    write_tabular("s_scr_outcomes.tex", lines)


def t_variance(d: pd.DataFrame, gate: Gate) -> None:
    three = d[d["profile"].isin(["all0", "all2", "all4"])]
    shares = {m: sc.two_way_shares(three[three["model"] == m]) for m in cd.MODELS}
    ref = three[three["model"] == "Luna"][["profile", "p"]].copy()
    ref["total"] = [20 if (pr == "all2" and p >= 0.5) else 0 for pr, p in zip(ref.profile, ref.p)]
    shares_ref = sc.two_way_shares(ref)
    lines = [r"\begin{tabular}{@{}lrrrrr@{}}", r"\toprule",
             r" & \multicolumn{5}{c}{Share of the variation in the total (\%)} \\",
             r"\cmidrule(l){2-6}",
             r" & Partner & & Partner kind & Risk and & \\",
             r"Model & kind & Risk & $\times$ risk & interaction & Residual \\", r"\midrule"]

    def row(label, s):
        return (f"{label} & {pct(s['profile'])} & {pct(s['risk'])} & {pct(s['inter'])} & "
                f"{pct(s['risk'] + s['inter'])} & {pct(s['resid'])}" + r" \\")

    for m in cd.MODELS:
        lines.append(row(cd.show(m), shares[m]))
    lines += [r"\midrule", row("Best response", shares_ref), r"\bottomrule", r"\end{tabular}"]
    write_tabular("s_scr_variance.tex", lines)
    four = ["Haiku", "Flash-Lite", "Luna", "Qwen"]
    prof = {m: pct(shares[m]["profile"]) for m in four}
    risk = {m: pct(shares[m]["risk"] + shares[m]["inter"]) for m in four}
    gate.macro("ScrOpponentShareMin", min(prof.values(), key=int))
    gate.macro("ScrOpponentShareMax", max(prof.values(), key=int))
    gate.macro("ScrRiskShareMax", max(risk.values(), key=int))
    gate.macro("ScrGrokOpponentShare", pct(shares["Grok"]["profile"]))
    gate.macro("ScrGrokRiskShare", pct(shares["Grok"]["risk"] + shares["Grok"]["inter"]))
    gate.macro("ScrGrokResidShare", pct(shares["Grok"]["resid"]))
    gate.macro("ScrBestResponderRiskShare", pct(shares_ref["risk"] + shares_ref["inter"]))


def t_settled(d: pd.DataFrame, gate: Gate) -> None:
    dom = d[d["profile"].isin(["all0", "all4"])]
    gate.macro("ScrDominatedGames", str(len(dom)))
    gate.macro("ScrBestResponseDominated", str(int((dom["total"] == 0).sum())))
    gate.macro("ScrMinTotalDominated", str(int(dom["total"].min())))
    rounds = sorted(int(s) for s in dom["settled"].unique())
    n = 9
    lines = [r"\begin{tabular}{@{}lrrlrrrlr@{}}", r"\toprule",
             r" & \multicolumn{4}{c}{Always 0} & \multicolumn{4}{c}{Always 4} \\",
             r"\cmidrule(lr){2-5}\cmidrule(l){6-9}",
             block("Games settled after each round, all five models (of 250)", n)]
    for t in rounds:
        c = [int((dom[dom.profile == k]["settled"] == t).sum()) for k in ("all0", "all4")]
        lines.append(f"Round {t} & " + " & ".join(rf"\multicolumn{{4}}{{c}}{{{v}}}" for v in c) + r" \\")
    lines += [r"\midrule",
              r" & \multicolumn{2}{c}{Units paid} & After: & No waste & "
              r"\multicolumn{2}{c}{Units paid} & After: & No waste \\",
              r"Model & Before & After & 95\% CI & (of 50) & Before & After & 95\% CI & (of 50) \\",
              r"\midrule"]
    for j, m in enumerate(cd.MODELS):
        cells = []
        clean = 0
        pooled = []
        for i, k in enumerate(("all0", "all4")):
            w = dom[(dom["model"] == m) & (dom["profile"] == k)]
            if len(w) != 50:
                raise AssertionError(f"{m} {k}: {len(w)} games")
            before = float(np.mean([int(x[: int(s)].sum()) for x, s in zip(w["x"], w["settled"])]))
            after = float(w["waste"].mean())
            lo, hi = cd.boot_ci(w["waste"], offset=OFF_SETTLED + 10 * i + j)
            zero = int((w["waste"] == 0).sum())
            clean += zero
            pooled += w["waste"].tolist()
            gate.settled[(m, k, "before")] = rnd(before)
            gate.settled[(m, k, "after")] = rnd(after)
            cells += [rnd(before), rnd(after), ci(lo, hi), str(zero)]
        lines.append(f"{cd.show(m)} & " + " & ".join(cells) + r" \\")
        gate.macro(f"ScrWaste{cd.MACRO[m]}", rnd(np.mean(pooled)))
        if m in ("Luna", "Qwen", "Grok"):
            gate.macro(f"ScrClean{cd.MACRO[m]}", pct(clean / len(pooled)))
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_tabular("s_scr_settled.tex", lines)


def one_way(df: pd.DataFrame, col: str, y: str = "total") -> float:
    gm = df[y].mean()
    sst = ((df[y] - gm) ** 2).sum()
    return float(((df.groupby(col)[y].transform("mean") - gm) ** 2).sum() / sst)


def t_grok(d: pd.DataFrame, gate: Gate, snum) -> None:
    d = d.copy()
    d["r1"] = [int(x[0]) for x in d["x"]]
    gk = d[d["model"] == "Grok"]
    lines = [r"\begin{tabular}{@{}lrrrrrr@{}}", r"\toprule",
             r" & \multicolumn{3}{c}{Games opening with} & \multicolumn{3}{c}{Mean total after opening with} \\",
             r"\cmidrule(lr){2-4}\cmidrule(l){5-7}",
             f"{cd.show('Grok')} beside & 0 & 2 & 4 & 0 & 2 & 4 " + r"\\", r"\midrule"]
    for label, w in [*((KIND_NAME[k], gk[gk.profile == k]) for k in KINDS), ("All four kinds", gk)]:
        if label == "All four kinds":
            lines.append(r"\midrule")
        counts = [int((w["r1"] == a).sum()) for a in sc.OPTIONS]
        means = [rnd(w[w["r1"] == a]["total"].mean()) if c else "" for a, c in zip(sc.OPTIONS, counts)]
        lines.append(f"{label} & " + " & ".join(map(str, counts)) + " & " + " & ".join(means) + r" \\")
    gate.macro("ScrGrokOpenFour", str(int((gk["r1"] == 4).sum())))
    lines += [r"\midrule",
              r" & \multicolumn{6}{c}{Share of the variation in the total explained by (\%)} \\",
              r"\cmidrule(l){2-7}",
              r"Model & \multicolumn{2}{c}{Opening move} & \multicolumn{2}{c}{Partner kind} & "
              r"\multicolumn{2}{c}{Risk} \\", r"\midrule"]
    for m in cd.MODELS:
        w = d[d["model"] == m]
        if len(w) != 200:
            raise AssertionError(f"{m}: {len(w)} games")
        s = [one_way(w, c) for c in ("r1", "profile", "p")]
        lines.append(f"{cd.show(m)} & " + " & ".join(rf"\multicolumn{{2}}{{c}}{{{pct(v)}}}" for v in s) + r" \\")
        if m == "Grok":
            gate.macro("ScrGrokFirstMoveShare", pct(s[0]))
            gate.macro("ScrGrokProfileShareFour", pct(s[1]))
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_tabular("s_scr_grok.tex", lines)
    others = d[d["model"] != "Grok"]
    if not (others["r1"] == 2).all():
        raise AssertionError("a model other than Grok 4.20 opened with 0 or 4")
    snum.add("SupScrOthersOpenTwo", str(len(others)))
    for a, name in ((2, "Two"), (4, "Four")):
        w = gk[gk["r1"] == a]
        snum.add(f"SupScrGrokRepeat{name}", rnd(np.mean([int((x == a).sum()) for x in w["x"]])))


def t_fair(d: pd.DataFrame, gate: Gate) -> None:
    n = 7
    lines = [r"\begin{tabular}{@{}lrrlrrr@{}}", r"\toprule",
             r" & Reached & Mean & \multicolumn{2}{c}{Most common sequence} & "
             r"\multicolumn{2}{c}{Most common shortfall} \\",
             r"\cmidrule(lr){4-5}\cmidrule(l){6-7}",
             r"Model & (of 50) & total & Own moves, rounds 1 to 10 & Games & Units & Games \\",
             r"\midrule"]
    for i, k in enumerate(("all2", "cond")):
        if i:
            lines.append(r"\midrule")
        lines.append(block(KIND_NAME[k], n))
        for m in cd.MODELS:
            w = d[(d.profile == k) & (d.model == m)]
            seqs, cnt = modes(tuple(int(a) for a in x) for x in w["x"])
            miss = w[w["reached"] == 0]
            if len(miss):
                shorts, scnt = modes(int(T - g) for g in miss["G"])
                s_units = " or ".join(map(str, shorts))
                s_games = f"{scnt} each" if len(shorts) > 1 else str(scnt)
            else:
                s_units = s_games = ""
            games = f"{cnt} each" if len(seqs) > 1 else str(cnt)
            lines.append(f"{cd.show(m)} & {int(w['reached'].sum())} & {rnd(w['total'].mean())} & "
                         f"{' or '.join(seq(s) for s in seqs)} & {games} & {s_units} & {s_games}" + r" \\")
            if k == "all2" and m == "Qwen":
                if not len(miss) or len(shorts) != 1:
                    raise AssertionError("Qwen3-235B shortfall beside always-2 partners is not unique")
                gate.macro("ScrQwenFairShort", s_units)
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_tabular("s_scr_fair.tex", lines)


def t_free(d: pd.DataFrame, gate: Gate) -> None:
    a0 = d[d["profile"] == "all0"]
    if a0["reached"].any():
        raise AssertionError("a game beside always-0 partners reached the target")
    lines = [r"\begin{tabular}{@{}lrrrrrrl@{}}", r"\toprule",
             r" & \multicolumn{5}{c}{Risk $p$} & \multicolumn{2}{c}{All risks} \\",
             r"\cmidrule(lr){2-6}\cmidrule(l){7-8}",
             "Model & " + " & ".join(ptxt(p) for p in RISKS) + r" & Mean & 95\% CI \\", r"\midrule"]
    # Beside always-0 partners the best response is 0 and the target is never reached, so
    # this gap equals the gap to the best response, game by game. Same sample, same offset
    # as s_scr_outcomes, so the two tables print the same interval.
    if not np.allclose(a0["free_rider_gap"], a0["gap"]):
        raise AssertionError("always-0 seat advantage differs from the best-response gap")
    pooled = {}
    for j, m in enumerate(cd.MODELS):
        w = a0[a0["model"] == m]
        by = w.groupby("p")["free_rider_gap"].mean()
        lo, hi = cd.boot_ci(w["free_rider_gap"], offset=OFF_OUTCOMES + 10 * KINDS.index("all0") + j)
        pooled[m] = rnd(w["free_rider_gap"].mean())
        lines.append(f"{cd.show(m)} & " + " & ".join(rnd(by[p]) for p in RISKS) +
                     f" & {pooled[m]} & {ci(lo, hi)}" + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write_tabular("s_scr_free.tex", lines)
    vals = {m: float(a0[a0.model == m]["free_rider_gap"].mean()) for m in cd.MODELS}
    gate.macro("ScrFreeRiderGapMin", pooled[min(vals, key=vals.get)])
    gate.macro("ScrFreeRiderGapMax", pooled[max(vals, key=vals.get)])


# ------------------------------------------------------------------ figure
def figure(d: pd.DataFrame) -> None:
    """Mean units paid per round beside always-2 and copy-the-group partners, low risk
    (p = 0.1, 0.3) and high risk (p = 0.7, 0.9). Top row: the best response's mean
    payment per round; below p* that is 0, above it every sequence totalling 20 is a best
    response, and their round-by-round mean is 2 by symmetry."""
    rows = ["Best response", *cs.MODEL_ORDER]
    cs.use()
    fig = plt.figure(figsize=cs.figsize("full", height_pt=215))
    fig._crsd_width = "full"
    axes = fig.subplots(2, 2, sharex=True, sharey=True)
    norm = mpl.colors.Normalize(0, max(sc.OPTIONS))
    bands = (("low", lambda p: p < 0.5, "$p<0.5$", 0.0), ("high", lambda p: p > 0.5, "$p>0.5$", 2.0))
    letters = iter("abcd")
    for r_i, k in enumerate(("all2", "cond")):
        for c_i, (_, keep, tex, br) in enumerate(bands):
            ax = axes[r_i, c_i]
            X = np.full((len(rows), R), br)
            for i, m in enumerate(cs.MODEL_ORDER, start=1):
                w = d[(d.profile == k) & (d.model == m) & d.p.map(keep)]
                S = np.stack(w["x"].to_list())
                if S.shape != (20, R):
                    raise AssertionError(f"{k} {m}: {S.shape}")
                X[i] = S.mean(axis=0)
            for (i, t), v in np.ndenumerate(X):
                fc = cs.CMAP_PAY(norm(v))
                ax.add_patch(Rectangle((t + 0.5, i - 0.5), 1, 1, fc=fc, ec=cs.WHITE, lw=0.8, zorder=2))
                ax.text(t + 1, i, f"{v:.1f}", ha="center", va="center", fontsize=cs.SIZE_SMALL,
                        color=cs.cell_ink(fc), zorder=3)
            ax.axhline(0.5, color=cs.WHITE, lw=2.5, zorder=4)
            ax.set_xlim(0.5, R + 0.5)
            ax.set_ylim(len(rows) - 0.5, -0.5)
            cs.style_matrix_axes(ax)
            ax.set_xticks([1, 4, 7, 10])
            if r_i == 1:
                ax.set_xlabel("Round")
            cs.panel_title(ax, next(letters), f"{KIND_NAME[k]}, {tex}")
        cs.row_labels(axes[r_i, 0], rows)
    sm = mpl.cm.ScalarMappable(norm=norm, cmap=cs.CMAP_PAY)
    cb = fig.colorbar(sm, ax=list(axes.ravel()), location="right", fraction=0.05, pad=0.02, aspect=20)
    cb.outline.set_visible(False)
    cb.set_ticks(list(sc.OPTIONS))
    cb.ax.tick_params(length=2.0, width=0.6, labelsize=cs.SIZE_SMALL)
    cb.set_label("Units paid per round", fontsize=cs.SIZE_LABEL)
    OUT_F.mkdir(parents=True, exist_ok=True)
    pdf = cs.save(fig, OUT_F / "sfig_scripted_rounds", title="sfig_scripted_rounds")
    plt.close(fig)
    print(f"wrote {pdf} (+ .png)")


# ------------------------------------------------------------------ main
def main() -> None:
    sys.stdout.reconfigure(encoding="utf-8")
    reach = sc.brute_force()
    d = sc.load(reach)
    print(f"games {len(d)}; replay of scripted seats matched every game; no parse failures")
    gate = Gate()
    gate.macro("ScrGames", sc.thousands(len(d)))
    snum = cd.Macros("supp_scripted.py")
    snum.add("SupScrSequences", sc.thousands(len(sc.OPTIONS) ** R))
    snum.add("SupScrGamesTotalZero", str(int((d["total"] == 0).sum())))

    best = t_best(reach, gate)
    change_max = t_totals(d, best, gate)
    snum.add("SupScrFairChangeMax", rnd(change_max))
    t_outcomes(d, best, gate)
    t_variance(d, gate)
    t_settled(d, gate)
    t_grok(d, gate, snum)
    t_fair(d, gate)
    t_free(d, gate)
    gate.check()

    OUT_T.mkdir(parents=True, exist_ok=True)
    path = OUT_T / "snum_scripted.tex"
    path.write_text("\n".join([HEADER, *(rf"\newcommand{{\{k}}}{{{v}}}" for k, v in snum.items.items())])
                    + "\n", encoding="utf-8")
    print(f"wrote {path}")
    for k, v in snum.items.items():
        print(f"  \\{k} = {v}")
    figure(d)


if __name__ == "__main__":
    main()
