"""Supplement tables: self-play across risk, prompt and decoding controls, design counts.

Run from the repository root:
    python paper/AAMAS/analysis/supp_selfplay.py

Writes (and nothing else):
    paper/AAMAS/supplement/tables/s_design_counts.tex    games, decisions, replies without the CONTRIBUTION: marker per design
    paper/AAMAS/supplement/tables/s_lottery.tex          the ten lottery draws and grid catastrophes
    paper/AAMAS/supplement/tables/s_grid_total.tex       mean seat total, models x risk
    paper/AAMAS/supplement/tables/s_grid_reach.tex       target reached (%), models x risk
    paper/AAMAS/supplement/tables/s_grid_exact.tex       exact split (%), models x risk
    paper/AAMAS/supplement/tables/s_grid_lost.tex        share of opt(p) lost (%), models x risk
    paper/AAMAS/supplement/tables/s_grid_models.tex      one row per model on the whole grid
    paper/AAMAS/supplement/tables/s_endgame.tex          end-of-game facts per model on the grid
    paper/AAMAS/supplement/tables/s_controls_shift.tex   shift of the mean seat total per control
    paper/AAMAS/supplement/tables/s_controls_goal.tex    base grid, neutral wording, goal stated by p
    paper/AAMAS/supplement/tables/s_controls_detail.tex  failure signatures per control
    paper/AAMAS/supplement/tables/s_nohint.tex           no hint against the rerun, p in {.1,.5,.9}
    paper/AAMAS/supplement/tables/snum_selfplay.tex      \\Sup... macros the supplement prose may quote
    paper/AAMAS/supplement/figures/sfig_seat_totals.pdf  distribution of seat totals on the grid

Every tabular is checked against the paper: a value that also appears in
tables/num_selfplay.tex, tables/tab_models.tex or tables/tab_robust.tex must print
identically here, or the script raises RuntimeError.

Conventions (crsd_data, selfplay): unit of analysis = game; payoffs are EXPECTED over the
catastrophe lottery; percentile bootstrap over games, stratified by risk cell when p is
pooled; permutation tests over games, within risk cell when p is pooled. All resampling
streams use offsets >= 5000, one fixed block per table. Reads results/ read-only; never
reads Legacy_Results/; never calls selfplay.main() or selfplay.figure().
"""
from __future__ import annotations

import pathlib
import re
import sys
from decimal import ROUND_HALF_UP, Decimal

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import crsd_data as cd  # noqa: E402
import crsd_style as cs  # noqa: E402
import selfplay as sp  # noqa: E402

rnd, thousands = sp.rnd, sp.thousands
MODELS = cd.MODELS
BASE = "exp_baseline"
ENDPOINTS = (0.1, 0.9)
RISKS = tuple(np.round(np.arange(0.0, 1.0001, 0.1), 1))
SUPP = cd.PAPER / "supplement"
OUT_T = SUPP / "tables"
OUT_F = SUPP / "figures"
HEADER = "% Generated by paper/AAMAS/analysis/supp_selfplay.py. Do not edit by hand."
MAX_ROWS = 45

# Reader-facing condition names, in the order the paper introduces them.
CONTROLS = [("Rerun", "exp_evprobe"), ("No hint", "exp_nohint"), ("Rewording 1", "exp_para1"),
            ("Rewording 2", "exp_para2"), ("Temperature zero", "exp_baseline_temp0"),
            ("Neutral wording", "exp_wording"), ("Goal stated", "exp_neutral")]
# Row names used by the paper's tab_robust.tex, mapped to the same experiments.
ROBUST_ROWS = {"Base": BASE, "Rerun": "exp_evprobe", "No hint": "exp_nohint",
               "Para.\\,1": "exp_para1", "Para.\\,2": "exp_para2",
               "Temp.\\,0": "exp_baseline_temp0", "Wording": "exp_wording",
               "Goal": "exp_neutral"}


# ------------------------------------------------------------------ formatting
def pc(x: float, digits: int = 0) -> str:
    """selfplay.pct, but a share that still rounds to 0.0 or 100.0 prints as <0.1 or >99.9."""
    s = sp.pct(x, digits)
    if "." in s and float(s) in (0.0, 100.0) and not np.isclose(100.0 * x, float(s)):
        tail = "0." + "0" * (len(s.split(".")[1]) - 1) + "1"
        return f"$<${tail}" if float(s) == 0.0 else f"$>${100 - float(tail):g}"
    return s


def fmt_p(p: float) -> str:
    return "$<$0.001" if p < 0.001 else rnd(p, 4)


def ci(lo: float, hi: float, digits: int = 1) -> str:
    return f"[{rnd(lo, digits)}, {rnd(hi, digits)}]"


def half_up_int(x: float) -> int:
    return int(Decimal(repr(float(x))).quantize(Decimal(1), rounding=ROUND_HALF_UP))


def risk_list(ps) -> str:
    ps = sorted({round(float(p), 1) for p in ps})
    if len(ps) >= 5 and np.allclose(np.diff(ps), ps[1] - ps[0]):
        return f"${ps[0]:g}, {ps[1]:g}, \\dots, {ps[-1]:g}$"
    return "$" + ", ".join(f"{p:g}" for p in ps) + "$"


def model_header(first: str = "") -> list:
    """Two header lines naming the five models by family and member (as tab_robust does)."""
    return [first + " & " + " & ".join(cd.LINES[m][0] for m in MODELS) + r" \\",
            " & " + " & ".join(cd.LINES[m][1] for m in MODELS) + r" \\"]


_SHORT = re.compile(r"(?<![\w.-])(Haiku|Luna|Flash-Lite|Qwen|Grok)(?![\w.-])")


def audit_text(name: str, text: str, body: list) -> None:
    for bad in ("--", "\u2013", "\u2014"):
        if bad in text:
            raise RuntimeError(f"{name}: forbidden dash {bad!r}")
    if re.search(r"exp_|\.csv|\bE\d\b|mix__|evprobe|nohint|para\d|temp0", text):
        raise RuntimeError(f"{name}: internal name in reader-facing text")
    rows = [ln for ln in body if ln.rstrip().endswith("\\\\")]
    if len(rows) > MAX_ROWS:
        raise RuntimeError(f"{name}: {len(rows)} rows, limit {MAX_ROWS}")
    stripped = "\n".join(body)
    for full in cd.DISPLAY.values():
        stripped = stripped.replace(full, "")
    hit = _SHORT.search(stripped)
    if hit:
        raise RuntimeError(f"{name}: bare model name {hit.group(0)!r} in a table row")


def emit(name: str, colspec: str, head: list, body: list) -> pathlib.Path:
    lines = [HEADER, f"\\begin{{tabular}}{{{colspec}}}", r"\toprule", *head, r"\midrule",
             *body, r"\bottomrule", r"\end{tabular}"]
    text = "\n".join(lines) + "\n"
    audit_text(name, text, body)
    OUT_T.mkdir(parents=True, exist_ok=True)
    path = OUT_T / name
    path.write_text(text, encoding="utf-8")
    print(f"wrote {path.relative_to(cd.REPO)} ({sum(ln.endswith(chr(92) * 2) for ln in body)} body rows)")
    return path


# ------------------------------------------------------------------ consistency gate
class Gate:
    """Everything the supplement prints that the paper also prints must agree exactly."""

    def __init__(self):
        text = (cd.TABLES / "num_selfplay.tex").read_text(encoding="utf-8")
        self.macros = dict(re.findall(r"\\newcommand\{\\([A-Za-z]+)\}\{(.*)\}\s*$", text, flags=re.M))
        self.models = self._rows("tab_models.tex")
        self.robust = self._rows("tab_robust.tex")
        self.n = 0

    @staticmethod
    def _rows(filename):
        lines = (cd.TABLES / filename).read_text(encoding="utf-8").splitlines()
        start = lines.index(r"\midrule")
        stop = lines.index(r"\bottomrule")
        out = {}
        for ln in lines[start + 1:stop]:
            cells = [c.strip() for c in ln.rstrip().removesuffix("\\\\").split(" & ")]
            out[cells[0]] = cells[1:]
        return out

    def check(self, what: str, mine: str, paper: str) -> None:
        self.n += 1
        if str(mine) != str(paper):
            raise RuntimeError(f"supplement disagrees with the paper on {what}: "
                               f"supplement prints {mine!r}, paper prints {paper!r}")

    def macro(self, name: str, mine) -> None:
        if name not in self.macros:
            raise RuntimeError(f"macro \\{name} not found in num_selfplay.tex")
        self.check(f"\\{name}", str(mine), self.macros[name])

    def model_cell(self, m: str, col: int, mine: str, what: str) -> None:
        self.check(f"tab_models {cd.show(m)} {what}", mine, self.models[cd.show(m)][col])

    def robust_cell(self, row: str, m: str, mine: str, bold: bool) -> None:
        cell = self.robust[row][MODELS.index(m)]
        paper_bold = cell.startswith(r"\textbf{")
        value = cell[len(r"\textbf{"):-1] if paper_bold else cell
        self.check(f"tab_robust {row} / {cd.show(m)}", mine, value)
        self.check(f"tab_robust bold {row} / {cd.show(m)}", str(bold), str(paper_bold))


# ------------------------------------------------------------------ data helpers
def selfplay_games(games, exp, m):
    return games[(games.exp == exp) & games.models.map(lambda t, m=m: t == (m,))]


def stack(g):
    return np.stack(g.strat.to_list()).astype(int)                 # games x 6 x 10


def all_equal(traj, value):
    return all(a == value for a in traj)


# ================================================================== tables
def t_design_counts(games, units, seats, G, S):
    rows = [("Self-play grid", BASE), ("Rerun (in-game questions)", "exp_evprobe"),
            ("No hint", "exp_nohint"), ("Rewording 1", "exp_para1"), ("Rewording 2", "exp_para2"),
            ("Temperature zero", "exp_baseline_temp0"), ("Neutral wording", "exp_wording"),
            ("Goal stated", "exp_neutral")]
    scripted = [("Partners always pay 0", "exp_bestresponse_defect"),
                ("Partners always pay 2", "exp_bestresponse_coop"),
                ("Partners always pay 4", "exp_bestresponse_carry"),
                ("Partners copy the group", "exp_bestresponse_cond")]
    mixed = ("Two models at one table", "exp_mixed")

    tot = dict(games=0, dec=0, parse=0)
    counts = {}

    def line(label, e):
        g = games[games.exp == e]
        per_model = units[units.exp == e].groupby("model").size()
        if per_model.nunique() != 1 or len(per_model) != len(MODELS):
            raise RuntimeError(f"{label}: models do not play the same number of games")
        n_dec = int((seats.exp == e).sum()) * cd.N_ROUNDS
        n_parse = int(g.n_parse.sum())
        tot["games"] += len(g)
        tot["dec"] += n_dec
        tot["parse"] += n_parse
        counts[e] = len(g)
        return (f"{label} & {risk_list(g.p.unique())} & {thousands(per_model.iloc[0])} & "
                f"{thousands(len(g))} & {thousands(n_dec)} & {n_parse} \\\\")

    body = [line(label, e) for label, e in rows]
    body.append(r"One model, five scripted partners & & & & & \\")
    body += [line(r"\quad " + label, e) for label, e in scripted]
    body.append(line(*mixed))
    body += [r"\midrule",
             f"Total & & & {thousands(tot['games'])} & {thousands(tot['dec'])} & {tot['parse']} \\\\"]
    head = [r" & & Games per & Total & Model & Without the \\",
            r"Design & Risk levels $p$ & model & games & decisions & marker \\"]
    emit("s_design_counts.tex", "@{}llrrrr@{}", head, body)

    G.macro("CntGames", thousands(tot["games"]))
    G.macro("CntDecisions", thousands(tot["dec"]))
    G.macro("CntParseFail", str(tot["parse"]))
    G.macro("CntGamesBaseline", thousands(counts[BASE]))
    G.macro("CntGamesProbe", thousands(counts["exp_evprobe"]))
    G.macro("CntGamesNoCue", thousands(counts["exp_nohint"]))
    G.macro("CntGamesPara", thousands(counts["exp_para1"] + counts["exp_para2"]))
    G.macro("CntGamesTempZero", thousands(counts["exp_baseline_temp0"]))
    G.macro("CntGamesWording", thousands(counts["exp_wording"]))
    G.macro("CntGamesNeutral", thousands(counts["exp_neutral"]))
    G.macro("CntGamesScripted", thousands(sum(counts[e] for _, e in scripted)))
    G.macro("CntGamesMixed", thousands(counts["exp_mixed"]))
    if len(games) != tot["games"]:
        raise RuntimeError("design rows do not cover every game")
    print(f"  designs: {tot['games']} games, {tot['dec']} decisions, {tot['parse']} without the marker")


def t_lottery(games, G, S):
    draws = cd.lottery_draws()
    missed = games[games.reached == 0]
    pred = np.array([draws[r] < p for r, p in zip(missed.rep, missed.p)])
    if (pred != missed.catastrophe.astype(bool).values).any() or games[games.reached == 1].catastrophe.any():
        raise RuntimeError("catastrophe flags do not follow 'draw < p' on missed games")
    base = games[games.exp == BASE]
    body = []
    tm = tc = 0
    te = 0.0
    for rep, u in enumerate(draws):
        first = min(p for p in RISKS if p > u)
        b = base[(base.rep == rep) & (base.reached == 0)]
        n_m, n_c, n_e = len(b), int(b.catastrophe.sum()), float(b.p.sum())
        tm, tc, te = tm + n_m, tc + n_c, te + n_e
        body.append(f"{rep + 1} & {rnd(u, 3)} & $p \\ge {first:g}$ & {n_m} & {n_c} & {rnd(n_e, 1)} \\\\")
    body += [r"\midrule", f"All & & & {tm} & {tc} & {rnd(te, 1)} \\\\"]
    head = [r" & & A missed game & \multicolumn{3}{c}{Self-play grid} \\",
            r"\cmidrule(l){4-6}",
            r" & & ends in & Missed & \multicolumn{2}{c}{Catastrophes} \\",
            r"Repetition & Draw & catastrophe at & games & Realised & Expected \\"]
    emit("s_lottery.tex", "@{}rrlrrr@{}", head, body)
    G.macro("LotRealCat", str(tc))
    G.macro("LotExpCat", str(half_up_int(te)))
    if not max(draws) < float(G.macros["LotMaxDraw"]):
        raise RuntimeError("a lottery draw is not below \\LotMaxDraw")
    high = base[(base.reached == 0) & (base.p >= cd.PSTAR)]
    if int(high.catastrophe.sum()) != len(high):
        raise RuntimeError("a missed grid game at p >= 0.5 escaped the catastrophe")
    S.add("SupLotMissed", str(tm))
    S.add("SupLotMissedHigh", str(len(high)))
    S.add("SupLotCatLow", str(tc - len(high)))
    print(f"  lottery: grid misses {tm} ({len(high)} at p>=0.5), catastrophes {tc}, expected {te:.2f}")


def grid_head(extra: str = "All"):
    n = len(RISKS)
    tail = " & " if extra else ""
    return [f" & \\multicolumn{{{n}}}{{c}}{{Catastrophe probability $p$}}{tail} \\\\",
            f"\\cmidrule(lr){{2-{n + 1}}}",
            "Model & " + " & ".join(f"{p:g}" for p in RISKS) + (f" & {extra}" if extra else "") + r" \\"]


def cellwise(base_u, m, fn):
    d = base_u[base_u.model == m]
    out = []
    for p in RISKS:
        c = d[d.p == p]
        if len(c) != 10:
            raise RuntimeError(f"{m} at p={p}: {len(c)} games, expected 10")
        out.append(fn(c))
    return out


def t_grid(games, units, seats, G, S):
    base_u = units[units.exp == BASE].copy()
    base_s = seats[seats.exp == BASE].copy()
    base_u["opt"] = cd.opt_payoff(base_u.p)
    spec = "@{}l" + "r" * len(RISKS) + "@{\\hspace{10pt}}r@{}"

    # ---- mean seat total
    opt_row = ["0" if p < cd.PSTAR else ("0 or 20" if np.isclose(p, cd.PSTAR) else "20") for p in RISKS]
    body = [r"\emph{Optimum} & " + " & ".join(opt_row) + r" \\"]
    for m in MODELS:
        vals = cellwise(base_u, m, lambda c: c.own.mean())
        body.append(cd.show(m) + " & " + " & ".join(rnd(v, 1) for v in vals) + r" \\")
        G.macro("GridZero" + m.replace("-", ""), rnd(vals[0], 1))
    emit("s_grid_total.tex", "@{}l" + "r" * len(RISKS) + "@{}", grid_head(extra=""), body)

    # ---- target reached
    body = []
    for m in MODELS:
        vals = cellwise(base_u, m, lambda c: c.reached.mean())
        allv = pc(base_u[base_u.model == m].reached.mean())
        G.model_cell(m, 2, allv, "Target (%)")
        body.append(cd.show(m) + " & " + " & ".join(pc(v) for v in vals) + f" & {allv} \\\\")
    emit("s_grid_reach.tex", spec, grid_head(), body)

    # ---- exact split, share of seats
    body = []
    for m in MODELS:
        s = base_s[base_s.model == m]
        vals = [s[s.p == p].traj.map(lambda t: all_equal(t, 2)).mean() for p in RISKS]
        if any((s.p == p).sum() != 60 for p in RISKS):
            raise RuntimeError(f"{m}: a grid cell does not hold 60 seats")
        allv = pc(s.traj.map(lambda t: all_equal(t, 2)).mean())
        G.model_cell(m, 1, allv, "Exact split (%)")
        if m == "Flash-Lite":
            G.macro("GridFlashExactPct", allv)
        body.append(cd.show(m) + " & " + " & ".join(pc(v) for v in vals) + f" & {allv} \\\\")
    emit("s_grid_exact.tex", spec, grid_head(), body)

    # ---- share of opt(p) lost
    def lost(c):
        return 1.0 - c.exp_pay.mean() / c.opt.mean()

    body = []
    for m in MODELS:
        vals = cellwise(base_u, m, lost)
        allv = pc(lost(base_u[base_u.model == m]))
        G.model_cell(m, 4, allv, "Lost (%)")
        body.append(cd.show(m) + " & " + " & ".join(pc(v) for v in vals) + f" & {allv} \\\\")
    panel = [lost(base_u[base_u.p == p]) for p in RISKS]
    panel_all = pc(lost(base_u))
    G.macro("GridLossPanelPct", panel_all)
    for m, key in (("Grok", "GridGrokLossPct"), ("Flash-Lite", "GridFlashLossPct"), ("Qwen", "GridQwenLossPct")):
        G.macro(key, pc(lost(base_u[base_u.model == m])))
    body += [r"\midrule", r"\emph{Panel} & " + " & ".join(pc(v) for v in panel) + f" & {panel_all} \\\\"]
    emit("s_grid_lost.tex", spec, grid_head(), body)


def t_grid_models(units, seats, G, S):
    sp._OFFSET[0] = 5000
    base_u = units[units.exp == BASE].copy()
    base_s = seats[seats.exp == BASE].copy()
    base_u["opt"] = cd.opt_payoff(base_u.p)
    base_u["loss"] = base_u.opt - base_u.exp_pay
    # Loss decomposition, exactly as in selfplay.main():
    reached = base_u.reached.values == 1
    below = base_u.p.values < cd.PSTAR
    A = np.where(reached, (base_u.G.values - cd.TARGET) / cd.N_PLAYERS, 0.0)
    B = np.where(below & reached, base_u.opt.values - cd.FAIR_TOTAL, 0.0) \
        + np.where(below & ~reached, base_u.loss.values, 0.0)
    C = np.where(~below & ~reached, base_u.loss.values, 0.0)
    if not np.allclose(A + B + C, base_u.loss.values):
        raise RuntimeError("loss decomposition does not add up")
    if (A < -1e-9).any() or (B < -1e-9).any() or (C < -1e-9).any():
        raise RuntimeError("negative loss component")
    base_u["A"], base_u["B"], base_u["C"] = A, B, C
    labels = {"A": "past 120", "B": "below $p^*$", "C": "missed"}

    def row(name, d, s, strata_zero, strata_lost, offset):
        d0 = d[d.p == 0]
        s0 = s[s.p == 0]
        own0 = d0.own.mean()
        lo0, hi0 = (cd.boot_ci(d0.own, offset=offset) if strata_zero is None
                    else sp.strat_boot_ci(d0.own, strata_zero))
        lost = 100.0 * (1.0 - d.exp_pay.mean() / d.opt.mean())
        lo, hi = sp.strat_boot_ci(d.exp_pay, strata_lost, stat="ratio", denom=d.opt)
        t = d.loss.sum()
        shares = {k: d[k].sum() / t for k in "ABC"}
        cells = [name, rnd(own0, 1), ci(lo0, hi0), f"{int((s0.own > 0).sum())}/{len(s0)}",
                 rnd(lost, 0), ci(lo, hi, 0), pc(shares["B"]), pc(shares["A"]), pc(shares["C"])]
        return cells, shares, (lo, hi)

    body = []
    for i, m in enumerate(MODELS):
        d = base_u[base_u.model == m]
        s = base_s[base_s.model == m]
        cells, shares, _ = row(cd.show(m), d, s, None, d.p, 5100 + i)
        G.model_cell(m, 0, cells[1], "Pays at p=0")
        G.model_cell(m, 4, cells[4], "Lost (%)")
        G.model_cell(m, 5, labels[max(shares, key=shares.get)], "Main loss")
        body.append(" & ".join(cells) + r" \\")
    strata_p = base_u.model + "|" + base_u.p.astype(str)
    cells, shares, (plo, phi) = row(r"\emph{Panel}", base_u, base_s,
                                    base_u[base_u.p == 0].model, strata_p, 0)
    G.macro("GridZeroPaying", cells[3].split("/")[0])
    G.macro("GridZeroSeats", cells[3].split("/")[1])
    G.macro("GridLossPanelPct", cells[4])
    body += [r"\midrule", " & ".join(cells) + r" \\"]
    head = [r" & \multicolumn{3}{c}{At $p{=}0$} & \multicolumn{2}{c}{Payoff lost} & "
            r"\multicolumn{3}{c}{Share of the loss (\%)} \\",
            r"\cmidrule(lr){2-4}\cmidrule(lr){5-6}\cmidrule(l){7-9}",
            r" & Mean & & Seats & & & Below & Past & Missed \\",
            r"Model & total & 95\% CI & paying & \% & 95\% CI & $p^*$ & 120 & at $p \ge p^*$ \\"]
    emit("s_grid_models.tex", "@{}lrlrrlrrr@{}", head, body)
    S.add("SupGridLostPanelLo", rnd(plo, 0))
    S.add("SupGridLostPanelHi", rnd(phi, 0))
    S.add("SupGridLossShareBelow", pc(shares["B"]))
    S.add("SupGridLossSharePast", pc(shares["A"]))
    S.add("SupGridLossShareMissed", pc(shares["C"]))


def t_endgame(games, G, S):
    base = games[games.exp == BASE]
    cols = {k: [] for k in ("z10", "sec_pct", "sec_n", "piv_pct", "piv_n", "two19", "reach_n",
                            "round", "waste", "miss", "pace", "reach_pct", "cf")}
    na = "n/a"
    tot_miss = tot_pace = 0
    for m in MODELS:
        g = selfplay_games(games, BASE, m)
        if len(g) != 110:
            raise RuntimeError(f"{m}: {len(g)} grid games")
        X = stack(g)
        pot = np.cumsum(X.sum(1), axis=1)
        z10 = X[:, :, 9] == 0
        p9 = pot[:, 8]
        sec9 = p9 >= cd.TARGET
        piv9 = (p9 >= 96) & (p9 < cd.TARGET)
        cols["z10"].append(pc(z10.mean()))
        cols["sec_pct"].append(pc(z10[sec9].mean()) if sec9.any() else na)
        cols["sec_n"].append(str(int(sec9.sum())))
        cols["piv_pct"].append(pc(z10[piv9].mean()) if piv9.any() else na)
        cols["piv_n"].append(str(int(piv9.sum())))
        cols["two19"].append(pc((X[:, :, :9] == 2).mean()))
        reached = pot[:, -1] >= cd.TARGET
        if not np.array_equal(reached, g.reached.values == 1):
            raise RuntimeError(f"{m}: pool and target flag disagree")
        cols["reach_n"].append(str(int(reached.sum())))
        cols["reach_pct"].append(pc(reached.mean()))
        pot_start = np.concatenate([np.zeros((len(g), 1)), pot[:, :-1]], axis=1)
        waste = (X.sum(1) * (pot_start >= cd.TARGET)).sum(1) / cd.N_PLAYERS
        if reached.any():
            secured = np.array([np.argmax(r >= cd.TARGET) + 1 for r in pot[reached]])
            cols["round"].append(rnd(secured.mean(), 1))
            cols["waste"].append(rnd(waste[reached].mean(), 1))
        else:
            cols["round"].append(na)
            cols["waste"].append(na)
        pos = g.p.values > 0
        miss = pos & ~reached
        on_pace = np.array([all(pt[t - 1] >= 12 * t for t in range(1, 10)) for pt in pot])
        cols["miss"].append(str(int(miss.sum())))
        cols["pace"].append(str(int((miss & on_pace).sum())))
        tot_miss += int(miss.sum())
        tot_pace += int((miss & on_pace).sum())
        Xcf = X.copy()
        Xcf[:, :, 9] = Xcf[:, :, 8]
        cols["cf"].append(pc((Xcf.sum(axis=(1, 2)) >= cd.TARGET).mean()))
        if m == "Qwen":
            G.macro("GridQwenLastZeroPct", cols["z10"][-1])
            G.macro("GridQwenRoundsOneNinePct", cols["two19"][-1])
            G.macro("GridQwenReach", cols["reach_n"][-1])
            G.macro("GridQwenFixReachPct", cols["cf"][-1])
            # The paper says paying nothing in round 10 is also an equilibrium of that round
            # for almost every Qwen3-235B table: true exactly when the pool after round 9 is
            # short of 120 by more than the 4 units one seat can add.
            beyond_one = (p9 < cd.TARGET) & (cd.TARGET - p9 > 4)     # 4: most one seat can pay
            S.add("SupQwenShortBeyondOne", str(int(beyond_one.sum())))
            S.add("SupQwenModalPoolNine", str(int(np.bincount(p9.astype(int)).argmax())))
        if m == "Grok":
            G.macro("GridGrokSecuredRound", cols["round"][-1])
            G.macro("GridGrokWaste", rnd(waste.mean(), 1))       # the paper averages all games
            G.check("Grok waste over reached games equals all games", cols["waste"][-1], rnd(waste.mean(), 1))
        if m == "Haiku":
            G.macro("GridHaikuStopPct", cols["sec_pct"][-1])
            G.macro("GridHaikuStopOtherPct", cols["piv_pct"][-1])
            S.add("SupHaikuStopGames", cols["sec_n"][-1])
            S.add("SupHaikuStopOtherGames", cols["piv_n"][-1])
        if m == "Luna":
            G.macro("GridLunaMiss", cols["miss"][-1])
            G.macro("GridLunaGames", str(int(pos.sum())))
        G.model_cell(m, 2, cols["reach_pct"][-1], "Target (%)")
    G.macro("GridMissTotal", str(tot_miss))
    G.macro("GridMissOnPace", str(tot_pace))

    def r(label, key):
        return label + " & " + " & ".join(cols[key]) + r" \\"

    body = [
        r("Seats paying 0 in round 10 (\\%)", "z10"),
        r("\\quad when the pool after round 9 is at least 120 (\\%)", "sec_pct"),
        r("\\qquad games in this case", "sec_n"),
        r("\\quad when it is 96 to 118 (\\%)", "piv_pct"),
        r("\\qquad games in this case", "piv_n"),
        r("Decisions paying 2 in rounds 1 to 9 (\\%)", "two19"),
        r"\addlinespace",
        r("Games reaching 120 (of 110)", "reach_n"),
        r("\\quad mean round the pool first reached 120", "round"),
        r("\\quad units per seat paid after that round", "waste"),
        r("Games missing 120 at $p>0$ (of 100)", "miss"),
        r("\\quad of which at or ahead of fair pace through round 9", "pace"),
        r"\addlinespace",
        r("Games reaching 120 as played (\\%)", "reach_pct"),
        r("\\quad had every seat repeated its round-9 move in round 10 (\\%)", "cf"),
    ]
    emit("s_endgame.tex", "@{}l" + "r" * len(MODELS) + "@{}", model_header(), body)


def endpoint_units(units, e):
    d = units[(units.exp == e) & units.p.isin(ENDPOINTS)]
    cnt = d.groupby(["model", "p"]).size()
    if len(cnt) != 2 * len(MODELS) or (cnt != 10).any():
        raise RuntimeError(f"{e}: expected 10 games per model at p = 0.1 and 0.9")
    return d


def t_controls_shift(units, G, S):
    sp._OFFSET[0] = 6000
    base = endpoint_units(units, BASE)
    body = []
    n_bold = 0
    for k, m in enumerate(MODELS):
        b = base[base.model == m]
        base_val = rnd(b.own.mean(), 1)
        G.robust_cell("Base", m, base_val, False)
        if k:
            body.append(r"\midrule")
        body.append(f"{cd.show(m)} & Base grid & {base_val} & & & \\\\")
        for name, e in CONTROLS:
            d = endpoint_units(units, e)
            d = d[d.model == m]
            diff, pv = sp.strat_perm(b.own, b.p, d.own, d.p)
            lo, hi = sp.strat_boot_diff_ci(b.own, b.p, d.own, d.p)
            bold = pv < 0.01 and abs(diff) >= 2.0
            n_bold += bold
            val = rnd(d.own.mean(), 1)
            row = next(r for r, ex in ROBUST_ROWS.items() if ex == e)
            G.robust_cell(row, m, val, bold)
            shift = f"\\textbf{{{rnd(diff, 1)}}}" if bold else rnd(diff, 1)
            body.append(f" & {name} & {val} & {shift} & {ci(lo, hi)} & {fmt_p(pv)} \\\\")
    head = [r" & & Mean seat & Shift from & & \\",
            r"Model & Condition & total & base grid & 95\% CI & $P$ \\"]
    emit("s_controls_shift.tex", "@{}llrrlr@{}", head, body)
    S.add("SupShiftBoldCount", str(n_bold))


def t_controls_goal(units, seats, G, S):
    arms = [("Base grid", BASE), ("Neutral wording", "exp_wording"), ("Goal stated", "exp_neutral")]
    body = []
    offset = 7000
    paying0 = {e: 0 for _, e in arms}
    for j, p in enumerate((0.0, 0.1, 0.9)):
        if j:
            body.append(r"\midrule")
        body.append(f"\\multicolumn{{11}}{{@{{}}l}}{{$p = {p:g}$}} \\\\")
        for m in MODELS:
            cells = [r"\quad " + cd.show(m)]
            own = {}
            for _, e in arms:
                d = units[(units.exp == e) & (units.model == m) & (units.p == p)]
                s = seats[(seats.exp == e) & (seats.model == m) & (seats.p == p)]
                if len(d) != 10 or len(s) != 60:
                    raise RuntimeError(f"{e} {m} p={p}: {len(d)} games, {len(s)} seats")
                own[e] = d.own
                paying = int((s.own > 0).sum())
                if p == 0:
                    paying0[e] += paying
                cells += [rnd(d.own.mean(), 1), str(int(d.reached.sum())), str(paying)]
                key = m.replace("-", "")
                label = {0.0: "Zero", 0.1: "Low", 0.9: "High"}[p]
                if e == BASE and p == 0:
                    G.macro("GridZero" + key, cells[-3])
                elif e == "exp_wording":
                    G.macro("Wor" + label + key, cells[-3])
                elif e == "exp_neutral":
                    G.macro("Neu" + label + key, cells[-3])
            offset += 1
            cells.append(fmt_p(cd.perm_test(own["exp_wording"], own["exp_neutral"], offset=offset)))
            body.append(" & ".join(cells) + r" \\")
    for m in MODELS:
        key = m.replace("-", "")
        for e, prefix in (("exp_wording", "Wor"), ("exp_neutral", "Neu")):
            d = units[(units.exp == e) & (units.model == m)]
            G.macro(prefix + "Reach" + key, str(int(d.reached.sum())))
    G.macro("GridZeroPaying", str(paying0[BASE]))
    G.macro("WorZeroPaying", str(paying0["exp_wording"]))
    G.macro("NeuZeroPaying", str(paying0["exp_neutral"]))
    head = [r" & \multicolumn{3}{c}{Base grid} & \multicolumn{3}{c}{Neutral wording} & "
            r"\multicolumn{3}{c}{Goal stated} & \\",
            r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}\cmidrule(lr){8-10}",
            r" & Mean & Target & Seats & Mean & Target & Seats & Mean & Target & Seats & $P$, neutral \\",
            r"Model & total & (of 10) & paying & total & (of 10) & paying & total & (of 10) & paying & vs goal \\"]
    emit("s_controls_goal.tex", "@{}l" + "rrr" * 3 + "r@{}", head, body)
    s1 = seats[(seats.exp == "exp_neutral") & (seats.p == 0.1) & (seats.model == "Luna")]
    S.add("SupGoalLowPayingLuna", str(int((s1.own > 0).sum())))


def t_controls_detail(games, units, seats, G, S):
    conds = [("Base grid", BASE), *CONTROLS]
    macro_q = {BASE: "RobQwenLastZeroBase", "exp_nohint": "RobQwenLastZeroNoHint",
               "exp_para1": "RobQwenLastZeroParaOne", "exp_para2": "RobQwenLastZeroParaTwo",
               "exp_neutral": "RobQwenLastZeroNeutral", "exp_wording": "RobQwenLastZeroWording"}
    macro_g = {BASE: "RobGrokRiskBase", "exp_para2": "RobGrokRiskParaTwo", "exp_evprobe": "RobGrokRiskRerun"}
    macro_d = {BASE: "RobTempZeroBaseDistinct", "exp_baseline_temp0": "RobTempZeroDistinct"}
    body = []
    for i, (name, e) in enumerate(conds):
        s = seats[(seats.exp == e) & seats.p.isin(ENDPOINTS)]

        def share(m, fn):
            x = s[s.model == m]
            if len(x) != 120:
                raise RuntimeError(f"{e} {m}: {len(x)} endpoint seats")
            return pc(x.traj.map(fn).mean())

        q = share("Qwen", lambda t: t[-1] == 0)
        fl = share("Flash-Lite", lambda t: all_equal(t, 2))
        lu = share("Luna", lambda t: all_equal(t, 2))
        gk = share("Grok", lambda t: all_equal(t, 4))
        u = endpoint_units(units, e)
        g1 = u[(u.model == "Grok") & (u.p == 0.1)].own
        g9 = u[(u.model == "Grok") & (u.p == 0.9)].own
        step = rnd(g9.mean() - g1.mean(), 1)
        pv = cd.perm_test(g1, g9, offset=7100 + i)
        gg = games[(games.exp == e) & games.p.isin(ENDPOINTS)]
        per_cell = gg.groupby(["folder_model", "p"]).strat.apply(
            lambda col: len({tuple(map(tuple, x.astype(int))) for x in col}))
        if len(per_cell) != 2 * len(MODELS):
            raise RuntimeError(f"{e}: {len(per_cell)} endpoint cells")
        dist = rnd(per_cell.mean(), 1)
        if e in macro_q:
            G.macro(macro_q[e], q)
        if e in macro_g:
            G.macro(macro_g[e], step)
        if e == BASE:
            S.add("SupGrokStepBaseP", fmt_p(pv))
        if e == "exp_baseline_temp0":
            S.add("SupGrokStepTempZero", step)
            S.add("SupGrokStepTempZeroP", fmt_p(pv))
        if e in macro_d:
            G.macro(macro_d[e], dist)
        body.append(f"{name} & {q} & {fl} & {lu} & {gk} & {step} & {fmt_p(pv)} & {dist} \\\\")
        if e == "exp_baseline_temp0":
            S.add("SupTempZeroDistinctMin", str(int(per_cell.min())))
            S.add("SupTempZeroDistinctMax", str(int(per_cell.max())))
    fam = {m: cd.LINES[m][0] for m in MODELS}
    mem = {m: cd.LINES[m][1] for m in MODELS}
    head = [f" & {fam['Qwen']} & {fam['Flash-Lite']} & {fam['Luna']} & \\multicolumn{{3}}{{c}}{{{cd.show('Grok')}}} & \\\\",
            f" & {mem['Qwen']} & {mem['Flash-Lite']} & {mem['Luna']} & & & & \\\\",
            r"\cmidrule(lr){2-2}\cmidrule(lr){3-3}\cmidrule(lr){4-4}\cmidrule(lr){5-7}",
            r" & Pays 0 in & Exact & Exact & Pays 4 in & Total at 0.9 & & Distinct \\",
            r"Condition & round 10 (\%) & split (\%) & split (\%) & every round (\%) & minus at 0.1 & $P$ & games \\"]
    emit("s_controls_detail.tex", "@{}lrrrrrrr@{}", head, body)


def t_nohint(units, G, S):
    sp._OFFSET[0] = 8000
    ps = (0.1, 0.5, 0.9)
    arm = {e: units[(units.exp == e) & units.p.isin(ps)] for e in ("exp_evprobe", "exp_nohint")}
    for e, d in arm.items():
        if len(d) != 150 or (d.groupby("model").size() != 30).any():
            raise RuntimeError(f"{e}: expected 30 games per model")
    ev, nh = arm["exp_evprobe"], arm["exp_nohint"]
    measures = [("reached", "Target reached (\\% of games)", True),
                ("exp_pay", "Expected payoff per seat", False),
                ("own", "Mean seat total", False),
                ("exact2", "Exact split (\\% of seats)", True),
                ("exact4", "Pays 4 in every round (\\% of seats)", True)]
    body = []
    panel_pay_p = None
    for j, (col, title, share) in enumerate(measures):
        if j:
            body.append(r"\midrule")
        body.append(f"\\multicolumn{{5}}{{@{{}}l}}{{{title}}} \\\\")
        vals = {}
        for m in [*MODELS, None]:
            a = ev if m is None else ev[ev.model == m]
            b = nh if m is None else nh[nh.model == m]
            sa = a.model + "|" + a.p.astype(str)
            sb = b.model + "|" + b.p.astype(str)
            diff, pv = sp.strat_perm(a[col], sa, b[col], sb)
            if share:
                va, vb, vd = pc(a[col].mean()), pc(b[col].mean()), rnd(100 * diff, 0)
            else:
                va, vb, vd = rnd(a[col].mean(), 1), rnd(b[col].mean(), 1), rnd(diff, 1)
            name = r"\quad \emph{Panel}" if m is None else r"\quad " + cd.show(m)
            if m is None:
                body.append(r"\addlinespace")
            body.append(f"{name} & {va} & {vb} & {vd} & {fmt_p(pv)} \\\\")
            vals[m] = (va, vb)
            if m is None and col == "exp_pay":
                panel_pay_p = pv
        if col == "reached":
            G.macro("NoCueQwenReachBase", vals["Qwen"][0])
            G.macro("NoCueQwenReach", vals["Qwen"][1])
            G.macro("NoCuePanelReachBase", vals[None][0])
            G.macro("NoCuePanelReach", vals[None][1])
        if col == "exp_pay":
            G.macro("NoCueQwenPayBase", vals["Qwen"][0])
            G.macro("NoCueQwenPay", vals["Qwen"][1])
            G.macro("NoCuePanelPayBase", vals[None][0])
            G.macro("NoCuePanelPay", vals[None][1])
        if col == "exact2":
            S.add("SupNoHintHaikuExactBase", vals["Haiku"][0])
            S.add("SupNoHintHaikuExact", vals["Haiku"][1])
            G.macro("NoCueFlashExactPct", vals["Flash-Lite"][1])
            G.macro("NoCueLunaExactBasePct", vals["Luna"][0])
            G.macro("NoCueLunaExactPct", vals["Luna"][1])
        if col == "exact4":
            G.macro("NoCueGrokAllFourPct", vals["Grok"][1])
    head = [r" & & & No hint & \\",
            r"Measure and model & Rerun & No hint & minus rerun & $P$ \\"]
    emit("s_nohint.tex", "@{}lrrrr@{}", head, body)
    S.add("SupNoHintPanelPayP", fmt_p(panel_pay_p))


# ================================================================== figure
def figure(seats):
    base = seats[seats.exp == BASE]
    totals = np.arange(0, int(cd.ENDOWMENT) + 1, 2)
    cs.use()
    fig = plt.figure(figsize=cs.figsize("full", height_pt=330))
    fig._crsd_width = "full"
    grid = fig.add_gridspec(2, 3)
    im = None
    for k, m in enumerate(MODELS):
        r, c = divmod(k, 3)
        ax = fig.add_subplot(grid[r, c])
        H = np.zeros((len(RISKS), len(totals)))
        for i, p in enumerate(RISKS):
            s = base[(base.model == m) & (base.p == p)]
            if len(s) != 60:
                raise RuntimeError(f"{m} p={p}: {len(s)} seats")
            idx = (s.own.values // 2).astype(int)
            H[i] = np.bincount(idx, minlength=len(totals)) / len(s)
        if not np.allclose(H.sum(1), 1.0):
            raise RuntimeError(f"{m}: seat shares do not sum to one")
        im = ax.imshow(H, cmap=cs.CMAP_SEQ, vmin=0.0, vmax=1.0, aspect="auto")
        for i, p in enumerate(RISKS):
            opts = [0] if p < cd.PSTAR else ([0, 20] if np.isclose(p, cd.PSTAR) else [20])
            for o in opts:
                j = o // 2
                for ec, lw in ((cs.WHITE, 1.6), (cs.INK, 0.7)):
                    ax.add_patch(Rectangle((j - 0.5, i - 0.5), 1, 1, fill=False, ec=ec, lw=lw, zorder=3))
        ax.set_xticks([0, 5, 10, 15, 20], ["0", "10", "20", "30", "40"])
        ax.set_yticks(range(len(RISKS)))
        if c == 0:
            ax.set_yticklabels([f"{p:g}" for p in RISKS])
            ax.set_ylabel("Catastrophe probability $p$")
        else:
            ax.set_yticklabels([])
        ax.set_xlabel("Seat total (units)")
        cs.style_matrix_axes(ax)
        ax.tick_params(length=2.0)
        cs.panel_title(ax, "abcde"[k], cd.show(m))
        print(f"  figure {m:10s} share of seats at the optimum total: "
              f"{np.mean([H[i, 0 if p < .5 else 10] if not np.isclose(p, .5) else H[i, 0] + H[i, 10] for i, p in enumerate(RISKS)]):.2f}")
    key = fig.add_subplot(grid[1, 2])
    key.set_xticks([])            # axis("off") would leave invisible tick labels that the
    key.set_yticks([])            # overlap gate still measures
    key.grid(False)
    for spine in key.spines.values():
        spine.set_visible(False)
    cax = key.inset_axes([0.08, 0.62, 0.84, 0.09])
    cb = fig.colorbar(im, cax=cax, orientation="horizontal")
    cb.outline.set_visible(False)
    cb.ax.tick_params(length=2.0, width=0.6, labelsize=cs.SIZE_SMALL)
    cb.set_ticks([0, 0.25, 0.5, 0.75, 1.0], labels=["0", "0.25", "0.5", "0.75", "1"])
    cb.set_label("Share of the 60 seats in a cell", fontsize=cs.SIZE_LABEL)
    key.set_xlim(0, 1)
    key.set_ylim(0, 1)
    key.add_patch(Rectangle((0.08, 0.20), 0.07, 0.12, fc=cs.SEQ_ANCHORS[0], ec=cs.WHITE, lw=1.6, zorder=2))
    key.add_patch(Rectangle((0.08, 0.20), 0.07, 0.12, fill=False, ec=cs.INK, lw=0.7, zorder=3))
    key.text(0.19, 0.26, "Optimum total at that risk\n(both 0 and 20 at $p=0.5$)", ha="left", va="center",
             fontsize=cs.SIZE_SMALL, color=cs.INK)
    out = cs.save(fig, OUT_F / "sfig_seat_totals", width="full")
    plt.close(fig)
    print(f"wrote {out.relative_to(cd.REPO)} (cs.save checks passed)")


# ================================================================== main
class SupMacros(cd.Macros):
    def write_supp(self) -> pathlib.Path:
        OUT_T.mkdir(parents=True, exist_ok=True)
        path = OUT_T / "snum_selfplay.tex"
        existing = set()
        for f in cd.TABLES.glob("num_*.tex"):
            existing |= set(re.findall(r"\\newcommand\{\\([A-Za-z]+)\}", f.read_text(encoding="utf-8")))
        clash = [k for k in self.items if k in existing or not k.startswith("Sup")]
        if clash:
            raise RuntimeError(f"supplement macro names clash with the paper or lack the Sup prefix: {clash}")
        lines = [HEADER] + [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in self.items.items()]
        text = "\n".join(lines) + "\n"
        if "--" in text or "\u2013" in text or "\u2014" in text:
            raise RuntimeError("snum_selfplay.tex: forbidden dash")
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(cd.REPO)} ({len(self.items)} macros)")
        return path


def main():
    games, units, seats = sp.load()
    G = Gate()
    S = SupMacros("supp_selfplay.py")
    t_design_counts(games, units, seats, G, S)
    t_lottery(games, G, S)
    t_grid(games, units, seats, G, S)
    t_grid_models(units, seats, G, S)
    t_endgame(games, G, S)
    t_controls_shift(units, G, S)
    t_controls_goal(units, seats, G, S)
    t_controls_detail(games, units, seats, G, S)
    t_nohint(units, G, S)
    S.write_supp()
    for k, v in S.items.items():
        print(f"  \\{k} = {v}")
    print(f"consistency gate: {G.n} checks against num_selfplay.tex, tab_models.tex, tab_robust.tex passed")
    figure(seats)


if __name__ == "__main__":
    main()
