"""Supplementary tables for two models at one table and for selection among the models.

Run from the repository root (the selection bootstrap takes a few minutes):
    python paper/AAMAS/analysis/supp_groups.py

Reads results/exp_mixed, results/exp_baseline and results/exp_evprobe through the loaders of
mixed.py and selection.py (read-only; never Legacy_Results/, never writes under results/).
No module's main(), figure() or draw() is called, so the paper's figures and num_*.tex
macro files are left untouched. Writes ONLY
    paper/AAMAS/supplement/tables/s_mix_*.tex, s_sel_*.tex   (booktabs tabulars, no float)
    paper/AAMAS/supplement/tables/snum_groups.tex            (\\newcommand macros, prefix Sup)
    paper/AAMAS/supplement/figures/sfig_mass_beta.pdf (+ .png preview)

NUMBERS
    Unit = game. Payoffs are EXPECTED payoffs over the catastrophe lottery (crsd_data).
    Intervals are 95% percentile bootstraps over games. A number that the paper already
    prints is recomputed with the module's own bootstrap offset; new intervals use offsets
    >= 8000. Rounding is half-up on the decimal value.
    Before any file is written, every printed value that also exists in
    tables/num_mixed.tex, num_advantage.tex or num_selection.tex is compared with the macro
    at the macro's precision; a difference raises RuntimeError.

STATIONARY MASS
    Every mass in the tables is selection.outcome() (eigenvector of the embedded chain), as
    in the paper. Under strong selection some fixation probabilities fall below 1e-9 and
    the eigen solver sees more than one unit eigenvalue. Every mass is therefore recomputed
    with the Markov chain tree theorem in log space (exact for any beta), and the script
    refuses to write a table whose printed values the two methods do not share. The figure
    uses the tree theorem, checked against the eigen solver wherever the chain is well
    conditioned.
"""
from __future__ import annotations

import itertools
import re
import sys
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
from matplotlib.layout_engine import PlaceHolderLayoutEngine
from matplotlib.ticker import NullLocator
from scipy.special import logsumexp

sys.path.insert(0, str(Path(__file__).resolve().parent))
import crsd_data as cd       # noqa: E402
import crsd_style as cs      # noqa: E402
import mixed as mx_mod       # noqa: E402
import advantage as adv      # noqa: E402
import selection as sel      # noqa: E402

SUPP = cd.PAPER / "supplement"
OUT_TABLES = SUPP / "tables"
OUT_FIGURES = SUPP / "figures"
HEADER = "% Generated by paper/AAMAS/analysis/supp_groups.py. Do not edit by hand."
MACRO_FILES = ("num_mixed.tex", "num_advantage.tex", "num_selection.tex")
MAX_ROWS = 45

M = cd.MODELS
K = len(M)
MI = {m: i for i, m in enumerate(M)}
RISKS = sel.RISKS
PAIRS = list(itertools.combinations(M, 2))       # first-named model precedes in cd.MODELS
FOCAL = mx_mod.PANEL_B                            # Haiku, Flash-Lite, Luna, Qwen
MASS_SPECS = [("within", 0.1, 6), ("within", 1.0, 6), ("within", 10.0, 6),
              ("across", 0.1, 30), ("across", 1.0, 30), ("across", 10.0, 30),
              ("across", 1.0, 60), ("across", 10.0, 60), ("across", 1.0, 120), ("across", 10.0, 120)]
RULE_NAME = {"within": "One table", "across": "Many tables"}
SELF_SOURCE = {"pooled": "Self-play from the grid and the rerun (20 games per model and risk level)",
               "base": "Self-play from the grid only (10 games per model and risk level)"}
BETA_GRID = np.logspace(-2, 2, 81)


# ============================================================================ formatting
def rnd(x: float, digits: int) -> Decimal:
    """Half-up rounding of the decimal value (binary noise below 1e-12 is ignored)."""
    v = Decimal(f"{float(x):.12f}").quantize(Decimal(1).scaleb(-digits), rounding=ROUND_HALF_UP)
    return abs(v) if v == 0 else v


def num(x: float, digits: int = 1, plus: bool = False) -> str:
    v = rnd(x, digits)
    s = f"{abs(v):.{digits}f}"
    if v < 0:
        return "$-$" + s
    return ("$+$" + s) if (plus and v > 0) else s


def pct(share: float, digits: int = 0) -> str:
    return num(100.0 * share, digits)


def interval(lo: float, hi: float, digits: int = 1, scale: float = 1.0) -> str:
    return f"[{num(scale * lo, digits)}, {num(scale * hi, digits)}]"


def thousands(n: int) -> str:
    return f"{int(n):,}".replace(",", "{,}")


def show(m: str) -> str:
    return cd.show(m)


def model_header(first: str = "", n_before: int = 1) -> list:
    """Two header rows with the five model names split over two lines (cd.LINES)."""
    pad = " & " * (n_before - 1)
    top = pad + " & " + " & ".join(cd.LINES[m][0] for m in M) + r" \\"
    bottom = first + pad + " & " + " & ".join(cd.LINES[m][1] for m in M) + r" \\"
    return [top, bottom]


def group(text: str, ncols: int) -> str:
    return rf"\multicolumn{{{ncols}}}{{@{{}}l}}{{\textit{{{text}}}}} \\"


# ============================================================================ consistency gate
class Gate:
    """Compare printed values with the paper's macros, at the macro's precision."""

    def __init__(self):
        self.macros = {}
        for name in MACRO_FILES:
            text = (cd.TABLES / name).read_text(encoding="utf-8")
            for key, value in re.findall(r"^\\newcommand\{\\([A-Za-z]+)\}\{(.*)\}\s*$", text, re.M):
                self.macros[key] = value
        self.checked = []

    def number(self, name: str, value: float):
        if name not in self.macros:
            raise RuntimeError(f"gate: macro {name} not found in {MACRO_FILES}")
        raw = self.macros[name].replace("{,}", "").replace("$-$", "-")
        digits = len(raw.split(".")[1]) if "." in raw else 0
        mine = rnd(value, digits)
        if mine != Decimal(raw):
            raise RuntimeError(f"gate: \\{name} is {self.macros[name]} in the paper, this script prints {mine}")
        self.checked.append(name)

    def text(self, name: str, value: str):
        if self.macros.get(name) != value:
            raise RuntimeError(f"gate: \\{name} is {self.macros.get(name)!r} in the paper, this script prints {value!r}")
        self.checked.append(name)


# ============================================================================ writing
class Tables:
    def __init__(self):
        self.files = {}

    def add(self, name: str, colspec: str, lines: list):
        body = [HEADER, rf"\begin{{tabular}}{{{colspec}}}", r"\toprule", *lines, r"\bottomrule", r"\end{tabular}"]
        text = "\n".join(body) + "\n"
        if "--" in text or chr(0x2013) in text or chr(0x2014) in text:
            raise RuntimeError(f"{name}: a dash that renders as an en or em dash")
        if re.search(r"exp_|\.csv|\.py", text.split("\n", 1)[1]):
            raise RuntimeError(f"{name}: internal name in reader-facing text")
        rows = sum(1 for line in body if line.rstrip().endswith(r"\\"))
        if rows > MAX_ROWS:
            raise RuntimeError(f"{name}: {rows} rows, the limit is {MAX_ROWS}")
        self.files[name] = (text, rows)

    def write(self):
        OUT_TABLES.mkdir(parents=True, exist_ok=True)
        for name, (text, rows) in self.files.items():
            (OUT_TABLES / name).write_text(text, encoding="utf-8")
            print(f"wrote {(OUT_TABLES / name).relative_to(cd.REPO)} ({rows} rows)")


# ============================================================================ mixed tables
def t_reach(mg, gate):
    lines = [r" & & \multicolumn{5}{c}{Seats held by the first model} & \\",
             r"\cmidrule(lr){3-7}",
             r"First model & Second model & 1 & 2 & 3 & 4 & 5 & All \\",
             r"\midrule"]
    for a, b in PAIRS:
        d = mg[(mg.A == a) & (mg.B == b)]
        cells = []
        for k in range(1, 6):
            dk = d[d.kA == k]
            if len(dk) != 30:
                raise RuntimeError(f"{a}/{b} k={k}: {len(dk)} games")
            cells.append(pct(dk.reached.mean()))
        if len(d) != 150:
            raise RuntimeError(f"{a}/{b}: {len(d)} games")
        cells.append(pct(d.reached.mean()))
        if (a, b) == ("Flash-Lite", "Qwen"):
            gate.number("AdvPairLowReachPct", 100 * d.reached.mean())
        lines.append(f"{show(a)} & {show(b)} & " + " & ".join(cells) + r" \\")
    lines.append(r"\midrule")
    cells = [pct(mg[mg.kA == k].reached.mean()) for k in range(1, 6)] + [pct(mg.reached.mean())]
    lines.append(r"All pairs & & " + " & ".join(cells) + r" \\")
    return lines


def t_reach_p(mg, su):
    lines = [r" & & \multicolumn{3}{c}{Risk $p$} \\",
             r"\cmidrule(l){3-5}",
             r"First model & Second model & 0.1 & 0.5 & 0.9 \\",
             r"\midrule"]
    for a, b in PAIRS:
        cells = []
        for p in RISKS:
            d = mg[(mg.A == a) & (mg.B == b) & (mg.p == p)]
            if len(d) != 50:
                raise RuntimeError(f"{a}/{b} p={p}: {len(d)} games")
            cells.append(pct(d.reached.mean()))
        lines.append(f"{show(a)} & {show(b)} & " + " & ".join(cells) + r" \\")
    lines += [r"\midrule", group("Self-play", 5)]
    for m in M:
        cells = []
        for p in RISKS:
            d = su[(su.model == m) & (su.p == p)]
            if len(d) != 20:
                raise RuntimeError(f"{m} self-play p={p}: {len(d)} games")
            cells.append(pct(d.reached.mean()))
        lines.append(f"{show(m)} & & " + " & ".join(cells) + r" \\")
    return lines


def t_edge(mx, sp, gate):
    edge, edge_ci, contrib_gap, reach, count, n = adv.matrices(mx, sp)
    lines = model_header("Row model") + [r"\midrule", group("Expected payoff per seat, row model minus column model", 6)]
    for i, m in enumerate(M):
        vals, cis = [], []
        for j in range(K):
            if i == j:
                vals.append(r"\textit{self}")
                cis.append("")
            else:
                vals.append(num(edge[i, j], 1, plus=True))
                cis.append(interval(*edge_ci[(i, j)], 1))
        lines.append(f"{show(m)} & " + " & ".join(vals) + r" \\")
        lines.append(" & " + " & ".join(cis) + (r" \\[2pt]" if i < K - 1 else r" \\"))
    lines += [r"\midrule", group("Units paid per seat, row model minus column model", 6)]
    for i, m in enumerate(M):
        vals = [r"\textit{self}" if i == j else num(contrib_gap[i, j], 1, plus=True) for j in range(K)]
        lines.append(f"{show(m)} & " + " & ".join(vals) + r" \\")
    # gate
    off = ~np.eye(K, dtype=bool)
    g, q = MI["Grok"], MI["Qwen"]
    grok_row = {M[j]: edge[g, j] for j in range(K) if j != g}
    worst = min(grok_row, key=grok_row.get)
    qwen_row = {M[j]: edge[q, j] for j in range(K) if j != q}
    best = max(qwen_row, key=qwen_row.get)
    gate.number("AdvGrokWorst", -grok_row[worst])
    gate.text("AdvGrokWorstPartner", show(worst))
    gate.number("AdvQwenBest", qwen_row[best])
    gate.text("AdvQwenBestPartner", show(best))
    gate.number("AdvMaxAbs", float(np.max(np.abs(edge[off]))))
    return lines, (edge, edge_ci, contrib_gap, reach, count, n)


def t_pairs(mats, gate):
    edge, edge_ci, contrib_gap, reach, count, n = mats
    lines = model_header("Model") + [r"\midrule"]
    for i, m in enumerate(M):
        cells = []
        for j in range(K):
            cell = f"{count[i, j]}/{n[i, j]}"
            cells.append(rf"\textit{{{cell}}}" if i == j else cell)
        lines.append(f"{show(m)} & " + " & ".join(cells) + r" \\")
    fq = (MI["Flash-Lite"], MI["Qwen"])
    gate.number("AdvPairLowReach", count[fq])
    gate.text("AdvPairLowReachName", f"{show('Flash-Lite')} and {show('Qwen')}")
    pairs = {(i, j): reach[i, j] for i, j in itertools.combinations(range(K), 2)}
    if min(pairs, key=pairs.get) != fq:
        raise RuntimeError("the lowest pair is no longer Gemini 3.5 Flash-Lite and Qwen3-235B")
    gate.number("MixFlashAloneReach", 100 * reach[MI["Flash-Lite"], MI["Flash-Lite"]])
    gate.number("MixLunaAloneReach", 100 * reach[MI["Luna"], MI["Luna"]])
    return lines


def t_lastround(mg, gate, snum):
    dec = []
    for g in mg.itertuples():
        if abs(g.pot[8] - mx_mod.POT_BEFORE_LAST) > 1e-9:
            continue
        for i, name in enumerate(g.names):
            dec.append(dict(gid=g.gid, model=name, x=g.strat[i, 9]))
    D = pd.DataFrame(dec)
    zero_ref, n_miss_ref, n_miss_q_ref, fix_share_ref = mx_mod.pivotal(mg)
    lines = [r"Model & Paid 0 (\%) & Decisions & Games \\", r"\midrule"]
    zero = {}
    for m in M:
        d = D[D.model == m]
        zero[m] = (d.x == 0).mean()
        if abs(zero[m] - zero_ref[m]) > 1e-12:
            raise RuntimeError(f"{m}: round-10 zero share disagrees with mixed.pivotal")
        lines.append(f"{show(m)} & {pct(zero[m], 1)} & {thousands(len(d))} & {d.gid.nunique()} \\\\")
    miss = mg[mg.reached == 0]
    with_q = miss[[("Qwen" in (a, b)) for a, b in zip(miss.A, miss.B)]]
    fixed = 0
    for g in with_q.itertuples():
        nz = sum(1 for i, name in enumerate(g.names) if name == "Qwen" and g.strat[i, 9] == 0)
        fixed += int(g.G + cd.FAIR_SHARE * nz >= cd.TARGET)
    if (len(miss), len(with_q)) != (n_miss_ref, n_miss_q_ref) or abs(fixed / len(with_q) - fix_share_ref) > 1e-12:
        raise RuntimeError("pivotal counts disagree with mixed.pivotal")
    lines += [r"\midrule",
              rf"\multicolumn{{3}}{{@{{}}l}}{{Two-model tables that missed the target}} & {len(miss)} \\",
              rf"\multicolumn{{3}}{{@{{}}l}}{{\quad with a {show('Qwen')} seat}} & {len(with_q)} \\",
              rf"\multicolumn{{3}}{{@{{}}l}}{{\quad\quad reaching 120 if {show('Qwen')} paid 2 instead of 0 in round 10}}"
              rf" & {fixed} ({pct(fixed / len(with_q))}\%) \\"]
    gate.number("MixQwenPotZeroPct", 100 * zero["Qwen"])
    gate.number("MixFlashPotZeroPct", 100 * zero["Flash-Lite"])
    gate.number("MixMissTotal", len(miss))
    gate.number("MixMissWithQwen", len(with_q))
    gate.number("MixQwenPivotalFix", 100 * fixed / len(with_q))
    snum["SupMixQwenPivotalFixed"] = str(fixed)
    return lines


def t_slack(mg, mu, su, gate):
    A = mx_mod.panel_a(mg, mu, su)
    B = mx_mod.panel_b(mu)
    bes = mx_mod.beside(mu)
    ncol = 7
    lines = [group("(a) Target reached", ncol),
             r" & \multicolumn{2}{c}{Six seats of the model} & \multicolumn{3}{c}{Five seats and one "
             + show("Qwen") + r" seat} & One seat and five \\",
             r"\cmidrule(lr){2-3}\cmidrule(lr){4-6}",
             r"Model & \% & 95\% CI & Reached & \% & 95\% CI & " + show("Qwen") + r" seats \\",
             r"\midrule"]
    for m in mx_mod.PANEL_A:
        r = A.loc[m]
        d = mu[(mu.model == "Qwen") & (mu.partner == m) & (mu.k == 5)]
        if len(d) != 30:
            raise RuntimeError(f"five Qwen + one {m}: {len(d)} games")
        rescue = int(d.reached.sum())
        lines.append(f"{show(m)} & {pct(r.alone)} & {interval(*r.alone_ci, 0, 100)} & {int(r.q_hits)}/{int(r.n_q)} & "
                     f"{pct(r.q)} & {interval(*r.q_ci, 0, 100)} & {rescue}/30 \\\\")
        if m == "Grok":
            gate.number("MixGrokRescuesQwen", rescue)
        if m == "Haiku":
            gate.number("MixHaikuRescuesQwen", rescue)
    gate.number("MixFlashQwenReach", A.loc["Flash-Lite", "q_hits"])
    gate.number("MixLunaQwenReach", A.loc["Luna", "q_hits"])
    gate.number("MixHaikuQwenReach", A.loc["Haiku", "q_hits"])
    gate.number("MixGrokQwenReach", A.loc["Grok", "q_hits"])
    gate.number("MixFlashAloneReach", 100 * A.loc["Flash-Lite", "alone"])
    gate.number("MixLunaAloneReach", 100 * A.loc["Luna", "alone"])

    lines += [r"\midrule", group("(b) Units paid per seat of the model, by the seats of the other model", ncol),
              r" & \multicolumn{5}{c}{Grok 4.20 seats} & Five seats of \\",
              r"\cmidrule(lr){2-6}",
              r"Model & 1 & 2 & 3 & 4 & 5 & another model \\",
              r"\midrule"]
    for mi, m in enumerate(FOCAL):
        d = B[B.model == m].sort_values("grok")
        others = mu[(mu.model == m) & (mu.k == 1) & (mu.partner != "Grok")].own.to_numpy(float)
        if len(others) != 90 or abs(others.mean() - bes[m][1]) > 1e-12:
            raise RuntimeError(f"{m}: one seat beside five non-Grok seats disagrees with mixed.beside")
        o_ci = cd.boot_ci(others, offset=8000 + mi)
        lines.append(f"{show(m)} & " + " & ".join(num(v, 1) for v in d.own) + f" & {num(others.mean(), 1)} \\\\")
        lines.append(" & " + " & ".join(interval(lo, hi, 1) for lo, hi in zip(d.lo, d.hi))
                     + f" & {interval(*o_ci, 1)} " + (r"\\[2pt]" if mi < len(FOCAL) - 1 else r"\\"))
    luna5 = B[(B.model == "Luna") & (B.grok == 5)].own.iloc[0]
    gate.number("MixLunaBesideFiveGrok", luna5)
    gate.number("MixFlashBesideFiveGrok", B[(B.model == "Flash-Lite") & (B.grok == 5)].own.iloc[0])
    gate.number("MixHaikuBesideFiveGrok", B[(B.model == "Haiku") & (B.grok == 5)].own.iloc[0])
    gate.number("MixLunaBesideOthers", bes["Luna"][1])

    lines += [r"\midrule", group("(c) Units paid by one seat of the model beside five seats of each other model", ncol)]
    lines += [row.replace(r" \\", r" & \\") for row in model_header("Model")] + [r"\midrule"]
    for mi, m in enumerate(FOCAL):
        vals, cis = [], []
        for pj, partner in enumerate(M):
            if partner == m:
                vals.append(r"\textit{self}")
                cis.append("")
                continue
            d = mu[(mu.model == m) & (mu.k == 1) & (mu.partner == partner)].own.to_numpy(float)
            if len(d) != 30:
                raise RuntimeError(f"one {m} seat beside five {partner}: {len(d)} games")
            vals.append(num(d.mean(), 1))
            if partner == "Grok":
                ref = B[(B.model == m) & (B.grok == 5)]
                cis.append(interval(float(ref.lo.iloc[0]), float(ref.hi.iloc[0]), 1))
                if abs(ref.own.iloc[0] - d.mean()) > 1e-12:
                    raise RuntimeError(f"{m} beside five Grok seats disagrees with mixed.panel_b")
            else:
                cis.append(interval(*cd.boot_ci(d, offset=8100 + 10 * mi + pj), 1))
        lines.append(f"{show(m)} & " + " & ".join(vals) + r" & \\")
        lines.append(" & " + " & ".join(cis) + (r" & \\[2pt]" if mi < len(FOCAL) - 1 else r" & \\"))
    return lines


def t_timing(mg, gate, snum):
    rows = []
    for g in mg.itertuples():                     # same definitions as mixed.timing_split
        if "Grok" not in (g.A, g.B):
            continue
        m = g.B if g.A == "Grok" else g.A
        idx = [i for i, name in enumerate(g.names) if name == m]
        pot_start = np.r_[0.0, np.cumsum(g.strat.sum(axis=0))[:-1]]
        before = pot_start < cd.TARGET
        sf = np.maximum(0.0, cd.FAIR_SHARE - g.strat[idx])
        rows.append(dict(model=m, early=sf[:, before].mean() if before.any() else np.nan,
                         late=sf[:, ~before].mean() if (~before).any() else np.nan,
                         tot_early=sf[:, before].sum(axis=1).mean(), tot_late=sf[:, ~before].sum(axis=1).mean()))
    T = pd.DataFrame(rows)
    ref = mx_mod.timing_split(mg)
    lines = [r" & \multicolumn{3}{c}{Before the pool reached 120} & \multicolumn{3}{c}{After the pool reached 120}"
             r" & \multicolumn{3}{c}{Units short per seat per game} \\",
             r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}\cmidrule(l){8-10}",
             r"Model & Per round & 95\% CI & Games & Per round & 95\% CI & Games & Before & After & After (\%) \\",
             r"\midrule"]
    for mi, m in enumerate(FOCAL):
        d = T[T.model == m]
        if len(d) != 150:
            raise RuntimeError(f"{m} beside Grok: {len(d)} games")
        e, l = d.early.mean(), d.late.mean()
        if abs(e - ref[m]["early"]) > 1e-12 or abs(l - ref[m]["late"]) > 1e-12:
            raise RuntimeError(f"{m}: timing split disagrees with mixed.timing_split")
        e_ci = cd.boot_ci(d.early.dropna(), offset=400 + mx_mod.PANEL_B.index(m))
        l_ci = cd.boot_ci(d.late.dropna(), offset=8200 + mi)
        te, tl = d.tot_early.mean(), d.tot_late.mean()
        share = tl / (te + tl)
        lines.append(f"{show(m)} & {num(e, 2)} & {interval(*e_ci, 2)} & {d.early.count()} & {num(l, 2)} & "
                     f"{interval(*l_ci, 2)} & {d.late.count()} & {num(te, 1)} & {num(tl, 1)} & {pct(share)} \\\\")
        snum[f"SupMixTiming{cd.MACRO[m]}AfterPct"] = pct(share)
    gate.number("MixLunaEarlyShort", ref["Luna"]["early"])
    gate.number("MixFlashEarlyShort", ref["Flash-Lite"]["early"])
    gate.number("MixHaikuEarlyShort", ref["Haiku"]["early"])
    return lines


# ============================================================================ stationary mass, exact
def _arborescences():
    """For every root, the K^(K-2) spanning trees with all edges directed towards it."""
    out = {}
    for root in range(K):
        others = [u for u in range(K) if u != root]
        valid = []
        for parents in itertools.product(range(K), repeat=K - 1):
            par = dict(zip(others, parents))
            if any(par[u] == u for u in others):
                continue
            ok = True
            for u in others:
                v, steps = u, 0
                while v != root and steps <= K:
                    v, steps = par[v], steps + 1
                if v != root:
                    ok = False
                    break
            if ok:
                valid.append([(u, par[u]) for u in others])
        if len(valid) != K ** (K - 2):
            raise RuntimeError(f"root {root}: {len(valid)} arborescences, Cayley says {K ** (K - 2)}")
        out[root] = np.array(valid)
    return out


TREES = _arborescences()


def log_rho(Pp, rule, N, beta):
    """L[x, y] = log fixation probability of one x newcomer in a y population (selection.py's
    formula, kept in logs)."""
    L = np.full((K, K), np.nan)
    i = np.arange(1, sel.N_WITHIN)
    for x, y in itertools.permutations(range(K), 2):
        if rule == "within":
            fx, fy = Pp[x, y, i], Pp[y, x, sel.N_WITHIN - i]
        else:
            fx, fy = sel.fitness(Pp, x, y, N)
        L[x, y] = -logsumexp(np.r_[0.0, -beta * np.cumsum(fx - fy)])
    return L


def tree_mass(L):
    """Markov chain tree theorem: mass of state s is proportional to the sum, over trees
    directed into s, of the product of transition probabilities u -> parent(u), where the
    move from resident u to model v happens at rate rho[v, u] / (K - 1)."""
    logw = np.empty(K)
    for root, trees in TREES.items():
        u, v = trees[:, :, 0], trees[:, :, 1]
        logw[root] = logsumexp(L[v, u].sum(axis=1))
    return np.exp(logw - logsumexp(logw))


def outcome_checked(Pp, reach, wel, rule, beta, N):
    o = sel.outcome(Pp, reach, wel, rule, beta, N)
    exact = tree_mass(log_rho(Pp, rule, N, beta))
    same_print = (all(rnd(a, 2) == rnd(b, 2) for a, b in zip(o["pi"], exact))
                  and rnd(100 * o["reach"], 0) == rnd(100 * exact @ reach, 0)
                  and rnd(o["pay"], 1) == rnd(exact @ wel, 1)
                  and int(np.argmax(exact)) == o["top"])
    if not same_print:
        raise RuntimeError(f"{rule} beta={beta} N={N}: eigen solver {o['pi']} and tree theorem {exact} "
                           "print differently")
    if o["n_unit"] == 1 and not np.allclose(o["pi"], exact, atol=1e-8):
        raise RuntimeError(f"{rule} beta={beta} N={N}: tree theorem disagrees with a well-conditioned chain")
    return o, exact


# ============================================================================ selection tables
def t_payoff(P, pi):
    lines = [r"Model & Beside & \multicolumn{6}{c}{Seats of the model at the table} \\",
             r"\cmidrule(l){3-8}",
             r" & & 1 & 2 & 3 & 4 & 5 & 6 \\",
             r"\midrule"]
    for xi, x in enumerate(M):
        partners = [y for y in M if y != x]
        for yi, y in enumerate(partners):
            vals = [P[pi, MI[x], MI[y], k] for k in range(1, 7)]
            if np.isnan(vals).any():
                raise RuntimeError(f"payoff function {x} beside {y} at p={RISKS[pi]} has a gap")
            end = r" \\[3pt]" if (yi == len(partners) - 1 and xi < K - 1) else r" \\"
            lines.append(f"{show(x) if yi == 0 else ''} & {show(y)} & " + " & ".join(num(v, 2) for v in vals) + end)
        if len({P[pi, MI[x], MI[y], 6] for y in partners}) != 1:
            raise RuntimeError(f"{x}: self-play entry differs across partners")
    return lines


def t_mass(P, REACH, WEL, point, gate, snum):
    lines = [r" & & & " + " & ".join(cd.LINES[m][0] for m in M) + r" & Target & Payoff \\",
             r"Population & $N$ & $\beta$ & " + " & ".join(cd.LINES[m][1] for m in M) + r" & (\%) & per seat \\",
             r"\midrule"]
    reducible, results = 0, {}
    for pi, p in enumerate(RISKS):
        if pi:
            lines.append(r"\midrule")
        lines.append(group(f"$p={p:g}$", 10))
        prev_rule = None
        for rule, beta, N in MASS_SPECS:
            o, exact = outcome_checked(P[pi], REACH[pi], WEL[pi], rule, beta, N)
            key = (rule, beta, N, pi)
            if key in point and not np.allclose(point[key]["pi"], o["pi"]):
                raise RuntimeError(f"{key}: mass disagrees with selection.run_rules")
            reducible += int(o["n_unit"] != 1)
            results[key] = o
            label = RULE_NAME[rule] if rule != prev_rule else ""
            prev_rule = rule
            lines.append(f"{label} & {N} & {beta:g} & " + " & ".join(num(v, 2) for v in o["pi"])
                         + f" & {pct(o['reach'])} & {num(o['pay'], 1)} \\\\")
        lines.append(r"Random model & & & " + " & ".join(num(1 / K, 2) for _ in M)
                     + f" & {pct(REACH[pi].mean())} & {num(WEL[pi].mean(), 1)} \\\\")
    lo, mid, hi = RISKS.index(0.1), RISKS.index(0.5), RISKS.index(0.9)
    for name, i in (("Low", lo), ("Mid", mid), ("High", hi)):
        gate.number(f"SelWithinQwenMass{name}", results[("within", 1.0, 6, i)]["pi"][MI["Qwen"]])
    gate.number("SelWithinReachHigh", 100 * results[("within", 1.0, 6, hi)]["reach"])
    gate.number("SelWithinReachMid", 100 * results[("within", 1.0, 6, mid)]["reach"])
    gate.number("SelWithinPayHigh", results[("within", 1.0, 6, hi)]["pay"])
    gate.number("SelAcrossFlashMassMid", results[("across", 1.0, 30, mid)]["pi"][MI["Flash-Lite"]])
    gate.number("SelAcrossFlashMassHigh", results[("across", 1.0, 30, hi)]["pi"][MI["Flash-Lite"]])
    gate.number("SelAcrossReachHigh", 100 * results[("across", 1.0, 30, hi)]["reach"])
    gate.number("SelAcrossPayHigh", results[("across", 1.0, 30, hi)]["pay"])
    gate.text("SelAcrossWinnerLow", show(M[results[("across", 1.0, 30, lo)]["top"]]))
    gate.number("SelUniformReachHigh", 100 * REACH[hi].mean())
    gate.number("SelUniformReachMid", 100 * REACH[mid].mean())
    gate.number("SelStrongWithinReachMid", 100 * results[("within", 10.0, 6, mid)]["reach"])
    gate.number("SelStrongWithinReachHigh", 100 * results[("within", 10.0, 6, hi)]["reach"])
    gate.number("SelWeakWithinMaxMass", max(float(results[("within", 0.1, 6, i)]["pi"].max()) for i in range(3)))
    gate.text("SelWeakAcrossTopHigh", show(M[results[("across", 0.1, 30, hi)]["top"]]))
    gate.text("SelWeakAcrossTopMid", show(M[results[("across", 0.1, 30, mid)]["top"]]))
    for (rule, beta, N) in MASS_SPECS:
        for i in range(3):
            ref = results[(rule, 1.0, 6 if rule == "within" else 30, i)]["top"]
            if beta != 0.1 and results[(rule, beta, N, i)]["top"] != ref:
                raise RuntimeError(f"winner changes under {(rule, beta, N)} at p={RISKS[i]}")
    snum["SupSelWeakWithinTopMid"] = show(M[results[("within", 0.1, 6, mid)]["top"]])
    snum["SupSelWeakWithinTopHigh"] = show(M[results[("within", 0.1, 6, hi)]["top"]])
    snum["SupSelIllConditioned"] = str(reducible)
    print(f"mass table: {reducible} rows where the eigen solver sees more than one unit eigenvalue; "
          "the tree theorem prints the same values")
    return lines


def t_boot(runs, gate, snum):
    lines = [r"Population & $p$ & Top model & Top in (\%) & Target (\%) & 95\% CI & Payoff per seat & 95\% CI \\",
             r"\midrule"]
    winners = {}
    for si, (source, (P, REACH, WEL, point, boots)) in enumerate(runs.items()):
        if si:
            lines.append(r"\midrule")
        lines.append(group(SELF_SOURCE[source], 8))
        shares = []
        for rule, beta, N in sel.RULES:
            for pi, p in enumerate(RISKS):
                o = point[(rule, beta, N, pi)]
                bs = boots[(rule, beta, N, pi)]
                if len(bs) != sel.N_BOOT:
                    raise RuntimeError(f"{source} {rule} p={p}: {len(bs)} bootstrap replicates")
                share = float(np.mean([b["top"] == o["top"] for b in bs]))
                shares.append(share)
                rlo, rhi = np.percentile([b["reach"] for b in bs], [2.5, 97.5])
                wlo, whi = np.percentile([b["pay"] for b in bs], [2.5, 97.5])
                winners[(source, rule, pi)] = o["top"]
                label = RULE_NAME[rule] if pi == 0 else ""
                lines.append(f"{label} & {p:g} & {show(M[o['top']])} & {pct(share)} & {pct(o['reach'])} & "
                             f"{interval(rlo, rhi, 0, 100)} & {num(o['pay'], 1)} & {interval(wlo, whi, 1)} \\\\")
        if source == "pooled":
            gate.number("SelBootMinPct", 100 * min(shares))
        else:
            snum["SupSelBaseBootMinPct"] = pct(min(shares))
    for rule, _, _ in sel.RULES:
        for pi in range(3):
            if winners[("pooled", rule, pi)] != winners[("base", rule, pi)]:
                raise RuntimeError(f"{rule} p={RISKS[pi]}: winner changes with the self-play source")
    snum["SupSelBootReps"] = thousands(sel.N_BOOT)
    return lines


def t_facts(mx, P, gate, snum):
    wins, below, n_cells, above = sel.table_facts(mx)
    lines = [group("(a) One seat beside five Grok 4.20 seats: expected payoff per seat", 5),
             r"Model & $p$ & One seat & Grok 4.20 seats & Ahead \\",
             r"\midrule"]
    ahead = 0
    for m in M:
        if m == "Grok":
            continue
        for pi, p in enumerate(RISKS):
            d = mx[(mx.p == p) & (((mx.A == m) & (mx.B == "Grok") & (mx.kA == 1))
                                  | ((mx.B == m) & (mx.A == "Grok") & (mx.kA == 5)))]
            if len(d) != 10:
                raise RuntimeError(f"{m} beside five Grok seats at p={p}: {len(d)} games")
            em = float(np.where(d.A == m, d.eA, d.eB).mean())
            eg = float(np.where(d.A == "Grok", d.eA, d.eB).mean())
            if abs(em - P[pi, MI[m], MI["Grok"], 1]) > 1e-12 or abs(eg - P[pi, MI["Grok"], MI[m], 5]) > 1e-12:
                raise RuntimeError(f"{m} beside five Grok seats disagrees with the payoff functions")
            if rnd(em, 2) == rnd(eg, 2):
                raise RuntimeError(f"{m} vs Grok at p={p}: tie at printed precision")
            ahead += int(em > eg)
            lines.append(f"{show(m) if pi == 0 else ''} & {p:g} & {num(em, 2)} & {num(eg, 2)} & "
                         f"{'One seat' if em > eg else show('Grok')} \\\\")
    if ahead != wins:
        raise RuntimeError("single-seat wins disagree with selection.table_facts")
    gate.number("SelGrokLosesCells", wins)

    lines += [r"\midrule",
              group(f"(b) {show('Qwen')} against its tablemates, exact one-sided sign-flip test per cell, "
                    f"$\\alpha={sel.ALPHA_SIG:g}$", 5),
              rf"\multicolumn{{4}}{{@{{}}l}}{{Cells (pair, seats, $p$) with {show('Qwen')} seats}} & {n_cells} \\",
              rf"\multicolumn{{4}}{{@{{}}l}}{{\quad {show('Qwen')} significantly below its tablemates}} & {len(below)} \\",
              rf"\multicolumn{{4}}{{@{{}}l}}{{\quad {show('Qwen')} significantly above its tablemates}} & {above} \\"]
    for c in below:
        other = c["B"] if c["A"] == "Qwen" else c["A"]
        q = c["qwen_seats"]
        lines.append(rf"\multicolumn{{5}}{{@{{}}l}}{{\quad\quad Below: $p={c['p']:g}$, {cd.word(q)} {show('Qwen')} "
                     rf"seat{'s' if q > 1 else ''} beside {cd.word(6 - q)} {show(other)} seat{'s' if 6 - q > 1 else ''}, "
                     rf"payoff gap {num(c['gap'], 2)}, one-sided $P={num(c['p_one_sided'], 3)}$}} \\")
    gate.number("SelQwenCells", n_cells)
    gate.text("SelQwenBelowCells", cd.word(len(below)))
    gate.number("SelQwenAboveCells", above)

    lines += [r"\midrule",
              group(r"(c) Winner by population size, $\beta=1$, $N$ from 6 to 120", 5),
              r"$p$ & \multicolumn{2}{l}{Winner at smaller $N$} & From $N$ & Winner up to $N=120$ \\",
              r"\midrule"]
    for pi, p in enumerate(RISKS):
        tops = {}
        for N in sel.N_SCAN:
            R = sel.rho_matrix(P[pi], N, sel.BETA)
            eig_top = int(np.argmax(sel.stationary(R)[0]))
            if eig_top != int(np.argmax(tree_mass(log_rho(P[pi], "across", N, sel.BETA)))):
                raise RuntimeError(f"p={p} N={N}: eigen solver and tree theorem pick different winners")
            tops[N] = M[eig_top]
        final = tops[max(sel.N_SCAN)]
        start = min(N for N in sel.N_SCAN if all(tops[n] == final for n in sel.N_SCAN if n >= N))
        if start != sel.switch_n(P, pi, target=final):
            raise RuntimeError(f"p={p}: population-size scan disagrees with selection.switch_n")
        earlier = [N for N in sel.N_SCAN if N < start]
        if earlier:
            names = sorted({tops[N] for N in earlier}, key=M.index)
            span = f"$N={earlier[0]}$" if len(earlier) == 1 else f"$N={earlier[0]}$ to ${earlier[-1]}$"
            before = ", ".join(show(n) for n in names) + f" ({span})"
        else:
            before = "none"
        lines.append(rf"{p:g} & \multicolumn{{2}}{{l}}{{{before}}} & {start} & {show(final)} \\")
        if p == 0.9:
            gate.number("SelSwitchN", start)
        if p == 0.5:
            snum["SupSelSwitchNMid"] = str(start)
    return lines


# ============================================================================ figure
def figure(P):
    cs.use()
    fig = plt.figure(figsize=cs.figsize("full", height_pt=270), layout="none")
    # A figure without an engine gets one back from rcParams (constrained, set by cs.use())
    # after its first savefig, which would re-lay the grid out between the PDF and the PNG.
    fig.set_layout_engine(PlaceHolderLayoutEngine(adjust_compatible=True, colorbar_gridspec=True))
    fig._crsd_width = "full"
    grid = fig.add_gridspec(2, 3, left=0.075, right=0.985, bottom=0.125, top=0.865, wspace=0.35, hspace=0.55)
    letters = iter("abcdef")
    colours = [cs.model(m).colour for m in M]
    worst = 0.0
    for ri, (rule, N) in enumerate((("within", sel.N_WITHIN), ("across", sel.N_ACROSS))):
        for ci, p in enumerate(RISKS):
            ax = fig.add_subplot(grid[ri, ci])
            mass = np.array([tree_mass(log_rho(P[ci], rule, N, b)) for b in BETA_GRID])
            for b, row in zip(BETA_GRID, mass):
                o = sel.outcome(P[ci], np.zeros(K), np.zeros(K), rule, b, N)
                if o["n_unit"] == 1:
                    worst = max(worst, float(np.abs(o["pi"] - row).max()))
            ax.stackplot(BETA_GRID, mass.T, colors=colours, edgecolor=cs.WHITE, linewidth=0.25, zorder=2)
            ax.axvline(sel.BETA, **{k: v for k, v in cs.THEORY.items() if k != "marker"})
            ax.set_xscale("log")
            ax.set_xlim(BETA_GRID[0], BETA_GRID[-1])
            ax.set_ylim(0, 1)
            ax.set_xticks([0.01, 0.1, 1, 10, 100], ["0.01", "0.1", "1", "10", "100"])
            ax.get_xticklabels()[0].set_horizontalalignment("left")    # clear of the y label "0"
            ax.xaxis.set_minor_locator(NullLocator())
            ax.set_yticks([0, 0.5, 1], ["0", "0.5", "1"])
            ax.grid(False)
            cs.panel_title(ax, next(letters), f"{RULE_NAME[rule]}, $N={N}$, $p={p:g}$")
            if ri == 1:
                ax.set_xlabel(r"Selection intensity $\beta$")
            if ci == 0:
                ax.set_ylabel("Stationary mass")
    if worst > 1e-6:
        raise RuntimeError(f"figure: tree theorem and eigen solver differ by {worst:.2e} on well-conditioned chains")
    print(f"figure: tree theorem vs eigen solver on well-conditioned chains, max abs difference {worst:.1e}")
    handles = [Patch(facecolor=c, edgecolor="none", label=show(m)) for m, c in zip(M, colours)]
    fig.legend(handles=handles, loc="upper center", bbox_to_anchor=(0.5, 0.995), ncols=K, frameon=False,
               handlelength=1.1, handleheight=0.8, columnspacing=1.4)
    return fig


# ============================================================================ main
def main():
    gate = Gate()
    tabs = Tables()
    snum = {}

    mg, mu, su = mx_mod.load()
    mx_mod.check_design(mg, mu, su)
    mx, sp = sel.load()
    if len(mx) != len(mg) or set(mx.gid) != set(mg.gid):
        raise RuntimeError("the two loaders see different mixed games")

    tabs.add("s_mix_reach.tex", r"@{}ll*{6}{r}@{}", t_reach(mg, gate))
    tabs.add("s_mix_reach_p.tex", r"@{}llrrr@{}", t_reach_p(mg, su))
    edge_lines, mats = t_edge(mx, sp, gate)
    tabs.add("s_mix_edge.tex", r"@{}l*{5}{c}@{}", edge_lines)
    tabs.add("s_mix_pairs.tex", r"@{}l*{5}{c}@{}", t_pairs(mats, gate))
    tabs.add("s_mix_lastround.tex", r"@{}lrrr@{}", t_lastround(mg, gate, snum))
    tabs.add("s_mix_slack.tex", r"@{}l*{6}{c}@{}", t_slack(mg, mu, su, gate))
    tabs.add("s_mix_timing.tex", r"@{}l*{9}{r}@{}", t_timing(mg, gate, snum))

    sel.identity_check(mx)
    mixed, selfc = sel.cell_arrays(mx, sp)
    # Same generator offsets as selection.main(); the replicates depend only on the draws in
    # selection.tables(), so boot_extra=False gives the paper's replicates for the two rules.
    runs = {"pooled": sel.run_rules(mixed, selfc, "POOLED self-play", offset=1, boot_extra=False)}
    _, selfc_base = sel.cell_arrays(mx, sp[sp.exp == "exp_baseline"])
    runs["base"] = sel.run_rules(mixed, selfc_base, "grid-only self-play", offset=2, boot_extra=False)
    P, REACH, WEL, point, boots = runs["pooled"]
    for pi, p in enumerate(RISKS):
        tabs.add(f"s_sel_payoff_p{int(round(10 * p)):02d}.tex", r"@{}ll*{6}{r}@{}", t_payoff(P, pi))
    tabs.add("s_sel_mass.tex", r"@{}lrr*{5}{c}rr@{}", t_mass(P, REACH, WEL, point, gate, snum))
    tabs.add("s_sel_boot.tex", r"@{}lrlrrcrc@{}", t_boot(runs, gate, snum))
    tabs.add("s_sel_facts.tex", r"@{}lrrrl@{}", t_facts(mx, P, gate, snum))

    # all gates passed: write
    tabs.write()
    lines = [HEADER]
    for key, value in snum.items():
        if not re.fullmatch(r"Sup[A-Za-z]+", key):
            raise ValueError(f"macro name {key!r}")
        lines.append(f"\\newcommand{{\\{key}}}{{{value}}}")
    (OUT_TABLES / "snum_groups.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {(OUT_TABLES / 'snum_groups.tex').relative_to(cd.REPO)}")
    for key, value in snum.items():
        print(f"  \\{key} = {value}")
    print(f"consistency gate: {len(set(gate.checked))} paper macros match: {', '.join(sorted(set(gate.checked)))}")

    fig = figure(P)
    pdf = cs.save(fig, OUT_FIGURES / "sfig_mass_beta", title="sfig_mass_beta")
    print(f"wrote {pdf.relative_to(cd.REPO)} (+ .png)")


if __name__ == "__main__":
    main()
