"""Render the verbatim prompts for the supplementary material.

Run from the repository root:
    python paper/AAMAS/supplement/make_prompts.py

Writes paper/AAMAS/supplement/prompts.tex. The text comes from the task that produced the
data (kaggle/benchmarks/crg_task_server.py), rendered offline for one example state, so
the supplement cannot drift from the prompts the models actually saw. No model is called.
"""
from __future__ import annotations

import difflib
import importlib.util
import os
import pathlib
import tempfile

REPO = pathlib.Path(__file__).resolve().parents[3]
TASK = REPO / "kaggle" / "benchmarks" / "crg_task_server.py"
OUT = pathlib.Path(__file__).resolve().parent / "prompts.tex"

# One example state: seat 3, round 3, p = 0.9, a short history.
STATE = dict(language="en", player_index=2, current_round=3,
             history=[[2, 2, 2, 2, 4, 2], [2, 0, 2, 2, 4, 2]], risk=0.9)
VARIANTS = ("baseline", "nohint", "wording", "neutral", "para1", "para2")
HINT_SPANS = ("(an average of 2 per player per round)",
              "(for example, contributing 2 every round leaves you 20 at the end)")
NORM_SPANS = ("simulates a collective-risk social dilemma", '"climate account"', "must reach",
              "the group is hit by a disaster and", "climate account", "the target is reached")

LATEX_ESC = {"\\": r"\textbackslash{}", "{": r"\{", "}": r"\}", "$": r"\$", "&": r"\&",
             "#": r"\#", "_": r"\_", "%": r"\%", "~": r"\textasciitilde{}",
             "^": r"\textasciicircum{}", "<": r"\textless{}", ">": r"\textgreater{}",
             '"': r"\textquotedbl{}"}


def esc(text: str) -> str:
    return "".join(LATEX_ESC.get(ch, ch) for ch in text)


def render_all() -> dict:
    os.environ["CRG_SKIP_RUN"] = "1"
    os.environ["CRG_LANGS"] = "en"
    here = os.getcwd()
    os.chdir(tempfile.mkdtemp())        # the task decorator writes a .task.json into CWD
    try:
        out = {}
        for v in VARIANTS:
            os.environ["CRG_TEMPLATE"] = v
            spec = importlib.util.spec_from_file_location(f"crg_supp_{v}", TASK)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            out[v] = mod.assemble_prompt(**STATE)
        return out
    finally:
        os.chdir(here)


def boxed(text: str, marks=()) -> str:
    """A prompt as a framed block that keeps its line breaks; marked spans in bold."""
    out = []
    for line in text.split("\n"):
        body = esc(line)
        for span in marks:
            body = body.replace(esc(span), r"\textbf{" + esc(span) + "}")
        out.append(body if body.strip() else r"\vspace{2pt}")
    return "\\begin{promptbox}\n" + "\\par\n".join(out) + "\n\\end{promptbox}\n"


def changes(base: str, other: str) -> str:
    """Line pairs that differ, as a two-column table: base line, then the changed line."""
    rows = []
    sm = difflib.SequenceMatcher(a=base.splitlines(), b=other.splitlines())
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            continue
        old = [ln for ln in base.splitlines()[i1:i2] if ln.strip()]
        new = [ln for ln in other.splitlines()[j1:j2] if ln.strip()]
        rows.append((old, new))

    def fmt(lines):
        return "\\newline ".join(esc(ln) for ln in lines)

    out = ["\\begin{description}[leftmargin=0pt]"]
    for old, new in rows:
        out.append("\\item[Base:] {\\ttfamily\\small\\raggedright "
                   + (fmt(old) or "(nothing)") + "\\par}")
        out.append("\\item[Changed to:] {\\ttfamily\\small\\raggedright "
                   + (fmt(new) or "(deleted)") + "\\par}")
    out.append("\\end{description}")
    return "\n".join(out).replace("\n\n", "\n")


def main() -> None:
    p = render_all()
    base = p["baseline"]
    parts = [
        "% Generated by paper/AAMAS/supplement/make_prompts.py. Do not edit by hand.",
        "\\subsection{Base prompt}",
        "The prompt one seat receives in round 3 at $p=0.9$ (the history is an example). The "
        "two equal-split phrases, which the no-hint prompt deletes, are in bold.",
        boxed(base, HINT_SPANS),
        "\\subsection{No hint}",
        "Identical to the base prompt except for the two lines below.",
        changes(base, p["nohint"]),
        "\\subsection{Neutral wording}",
        "Identical to the base prompt except for the lines below. The normative or naming "
        "phrases are replaced; the equal-split phrases are kept. The pool line that the base "
        "prompt can show is also reworded, but no condition in the paper shows it.",
        changes(base, p["wording"]),
        "\\subsection{Neutral wording, goal stated}",
        "The neutral-wording prompt with one opening paragraph added. Full text:",
        boxed(p["neutral"]),
        "\\subsection{Two rewordings}",
        "Both keep every rule, the equal-split phrases and the final instruction, and change "
        "only the phrasing.",
        "\\paragraph{Rewording 1.}",
        boxed(p["para1"], HINT_SPANS),
        "\\paragraph{Rewording 2.}",
        boxed(p["para2"], HINT_SPANS),
    ]
    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    assert p["neutral"].endswith(p["wording"]), "goal-stated prompt must be wording plus an opening"
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
